class inc(str):
	YEAR_INC				 = "In Millions of USD except Per Share"
	REV						 = "Revenue"
	SALES_SERV_REV			 = "Sales & Services Revenue"
	OTHER_REV				 = "Other Revenue"
	COST_OF_REV				 = "Cost of Revenue"
	COGS					 = "Cost of Goods & Services"
	PROFIT					 = "Gross Profit"
	OTH_PROFIT				 = "Other Operating Income"			
	OP_EXP					 = "Operating Expenses"		
	SG_AND_ADMIN			 = "Selling, General & Admin"
	SELL_AND_MARK			 = "Selling & Marketing"	
	GEN_AND_ADMIN			 = "General & Administrative"
	R_AND_D 				 = "Research & Development"
	DEP_AMORT				 = "Depreciation & Amortization"
	OTH_OP_EXP				 = "Other Operating Expense"
	OP_INC_LOSS				 = "Operating Income (Loss)"
	NON_OP_INC_LOSS			 = "Non-Operating (Income) Loss"
	NET_INT_EXP				 = "Interest Expense, Net"
	INT_EXP					 = "Interest Expense"
	INT_INC					 = "Interest Income"
	FOREX					 = "Foreign Exch (Gain) Loss"
	AFFILIATES				 = "(Income) Loss from Affiliates"
	NON_OP_INC				 = "Other Non-Op (Income) Loss"
	PRETAX_INCOME			 = "Pretax Income"
	INC_TAX_BENEFIT			 = "Income Tax Expense (Benefit)"
	CURR_INC_TAX			 = "Current Income Tax"
	DEFF_INC_TAX			 = "Deferred Income Tax"
	CONT_OPS				 = "Income (Loss) from Cont Ops"
	NET_EXTRA1				 = "Net Extraordinary Losses (Gains)"
	DISC_OPS				 = "Discontinued Operations"
	ACCT_CHNG				 = "XO & Accounting Changes"
	INCOME_MI				 = "Income (Loss) Incl. MI"
	MIN_INTEREST			 = "Minority Interest"
	NI_INC  			     = "Net Income, GAAP"
	PREF_DIVS				 = "Preferred Dividends"
	OTH_ADJ					 = "Other Adjustments"
	NI_AVAIL_COMMON_GAAP	 = "Net Income Avail to Common, GAAP"
	NI_AVAIL_COMMON_ADJ		 = "Net Income Avail to Common, Adj"
	NET_ABNORMAL			 = "Net Abnormal Losses (Gains)"
	NET_EXTRA2				 = "Net Extraordinary Losses (Gains)"
	BASIC_WEIGHT_AVG_SHARES  = "Basic Weighted Avg Shares"
	DIL_WEIGHT_AVG_SHARES	 = "Diluted Weighted Avg Shares"

class bal(str):
	YEAR_BAL					= "In Millions of USD except Per Share"
	TOTAL_ASSETS1				= "Total Assets"						 
	CASH_EQ_STI					= "Cash, Cash Equivalents & STI"		 
	CASH_EQ						= "Cash & Cash Equivalents"				 
	STI							= "ST Investments"						 
	ACCTS_REC					= "Accounts & Notes Receiv"				 
	ACCTS_REC_NET				= "Accounts Receivable, Net"			 
	NOTES_REC_NET				= "Notes Receivable, Net"				 
	INV							= "Inventories"							 
	RAW_MAT						= "Raw Materials"						 
	WIP							= "Work In Process"						 
	FIN_GOODS 					= "Finished Goods"						 
	OTH_INV						= "Other Inventory"						 
	OTH_ST_ASSETS				= "Other ST Assets"						 
	DERIV_HEDGE_ASSETS1			= "Derivative & Hedging Assets"		
	TAXES_RECIEV				= "Taxes Receivable"
	MISC_ST_ASSETS				= "Misc ST Assets"						 
	TOTAL_CURR_ASSETS			= "Total Current Assets"				 
	PPE_NET						= "Property, Plant & Equip, Net"		 
	PPE							= "Property, Plant & Equip"				 
	ACC_DEPREC					= "Accumulated Depreciation"			 
	LTI_RECEIVABLES				= "LT Investments & Receivables"
	LT_INVEST					= "LT Investments"
	OTH_LT_ASSETS				= "Other LT Assets"						 
	TOTAL_INT_ASSETS			= "Total Intangible Assets"				 
	GOODWILL					= "Goodwill"							 
	OTH_INT_ASSETS				= "Other Intangible Assets"	
	PREPAID_EXP					= "Prepaid Expense"
	DEFF_TAX_ASSETS				= "Deferred Tax Assets"					 
	DERIV_HEDGE_ASSETS2			= "Derivative & Hedging Assets"			 
	MISC_ASSETS					= "Misc LT Assets"						 
	TOTAL_NON_CURR_ASSETS		= "Total Noncurrent Assets"				 
	TOTAL_ASSETS2				= "Total Assets"						 
	LIAB_AND_EQUITY1			= "Liabilities & Shareholders' Equity"	 
	PAYABLES_ACCRUALS			= "Payables & Accruals"					 
	PAYABLES					= "Accounts Payable"					 
	ACCRUED_TAXES				= "Accrued Taxes"						 
	INT_DIVS_PAYABLES			= "Interest & Dividends Payable"		 
	OTH_PAYABLES_ACCURALS		= "Other Payables & Accruals"			 
	ST_DEBT						= "ST Debt"								 
	ST_BORROWINGS				= "ST Borrowings"						 
	ST_FIN_LEASES				= "ST Finance Leases"					 
	ST_OP_LEASES				= "ST Operating Leases"					 
	CURR_LT_DEBT				= "Current Portion of LT Debt"			 
	OTH_ST_LIAB					= "Other ST Liabilities"				 
	DEFF_REV_1					= "Deferred Revenue"					 
	DERIV_HEDGE_1				= "Derivatives & Hedging"				 
	MISC_ST_LIAB				= "Misc ST Liabilities"					 
	TOTAL_CURR_LIAB				= "Total Current Liabilities"			 
	LT_DEBT						= "LT Debt"								 
	LT_BORROW					= "LT Borrowings"						 
	LT_FIN_LEASES				= "LT Finance Leases"					 
	LT_OP_LEASES				= "LT Operating Leases"					 
	OTH_LT_LIAB					= "Other LT Liabilities"				 
	ACCURED_LIAB				= "Accrued Liabilities"					 
	PENSION_LIAB				= "Pension Liabilities"		
	PENSIONS					= "Pensions"
	OTH_POST_RET_BEN			= "Other Post-Ret Benefits"
	DEFF_REV_2					= "Deferred Revenue"
	DEF_TAX_LIAB				= "Deferred Tax Liabilities"
	DERIV_HEDGE_2				= "Derivatives & Hedging"				 
	MISC_LT_LIAB				= "Misc LT Liabilities"					 
	TOTAL_NON_CURR_LIAB			= "Total Noncurrent Liabilities"		 
	TOTAL_LIAB					= "Total Liabilities"					 
	PREF_EQUITY_HYBRID_CAP		= "Preferred Equity and Hybrid Capital"	 
	SHARE_CAP_APIC				= "Share Capital & APIC"				 
	COMMON_STOCK				= "Common Stock"						 
	ADD_PAID_CAP				= "Additional Paid in Capital"			 
	TREASURY_STOCK				= "Treasury Stock"						 
	RE							= "Retained Earnings"					 
	OTH_EQUITY					= "Other Equity"						 
	EQUITY_BEFORE_MIN_INT		= "Equity Before Minority Interest"		 
	MIN_NON_CONTROL_INT			= "Minority/Non Controlling Interest"	 
	TOTAL_EQUITY				= "Total Equity"						 
	LIAB_AND_EQUITY2			= "Total Liabilities & Equity"			 
	
class cf(str):
	YEAR_CF						 = "In Millions of USD except Per Share"
	NI_CF  						 = "Net Income"							  
	DEPRE_AMORT					 = "Depreciation & Amortization"			
	NON_CASH_ITEMS				 = "Non-Cash Items"						  
	STOCK_COMP					 = "Stock-Based Compensation"			  
	DEF_INT_COMP				 = "Deferred Income Taxes"				  
	OTH_NON_CASH_ADJ			 = "Other Non-Cash Adj"					  
	CHG_NON_CASH_OP				 = "Chg in Non-Cash Work Cap"			  
	CHG_ACCTS_REC				 = "(Inc) Dec in Accts Receiv"			  
	CHG_INVENTORIES				 = "(Inc) Dec in Inventories"			  
	CHG_ACCTS_PAYABLE			 = "Inc (Dec) in Accts Payable"			  
	CHG_OTHER					 = "Inc (Dec) in Other"					  
	NET_CASH_DISC_OPS1			 = "Net Cash From Disc Ops"				  
	CASH_OP_ACT					 = "Cash from Operating Activities"		  
	CASH_INVEST_ACT1			 = "Cash from Investing Activities"		  
	CHG_FIXED_INTANG			 = "Change in Fixed & Intang"			  
	DISP_FIXED_INTANG			 = "Disp in Fixed & Intang"				  
	DISP_FIXED_PROD_ASSETS		 = "Disp of Fixed Prod Assets"			  
	DISP_INTAG_ASSETS			 = "Disp of Intangible Assets"			  
	ACQ_FIXED_INTAG				 = "Acq of Fixed & Intang"				  
	ACQ_FIXED_PROD_ASSETS		 = "Acq of Fixed Prod Assets"			  
	ACQ_INTAG_ASSETS			 = "Acq of Intangible Assets"			  
	NET_CHG_LT_INVEST			 = "Net Change in LT Investment"			
	DEC_LT_INVEST				 = "Dec in LT Investment"				  
	INC_LT_INVEST				 = "Inc in LT Investment"				  
	NET_CASH_ACQ_DIV			 = "Net Cash From Acq & Div"				
	CASH_DIVEST					 = "Cash from Divestitures"				  
	CASH_ACQ_SUBS				 = "Cash for Acq of Subs"				  
	CASH_JVS					 = "Cash for JVs"						  
	OTH_INVEST_ACT				 = "Other Investing Activities"			  
	NET_CASH_DISC_OPS2			 = "Net Cash From Disc Ops"				  
	CASH_INVEST_ACT2			 = "Cash from Investing Activities"		  
	CASH_FIN_ACT1				 = "Cash from Financing Activities"		  
	DIVS_PAID					 = "Dividends Paid"						  
	CASH_REPAY_DEBT				 = "Cash From (Repayment) Debt"			  
	CASH_ST_DEBT				 = "Cash From (Repay) ST Debt"			  
	CASH_LT_DEBT				 = "Cash From LT Debt"					  
	REPAY_LT_DEBT				 = "Repayments of LT Debt"				  
	CASH_REPURCH_EQUITY			 = "Cash (Repurchase) of Equity"			
	INC_CAPITAL_STOCK			 = "Increase in Capital Stock"			  
	DEC_CAPITAL_STOCK			 = "Decrease in Capital Stock"			  
	OTH_FIN_ACT					 = "Other Financing Activities"			  
	NET_CASH_DISC_OPS3			 = "Net Cash From Disc Ops"				  
	CASH_FIN_ACT2				 = "Cash from Financing Activities"		  
	EFFECT_FOREX_RATES			 = "Effect of Foreign Exchange Rates"	  
	NET_CHG_CASH				 = "Net Changes in Cash"					
	CASH_PAID_TAXES				 = "Cash Paid for Taxes"					
	CASH_PAID_INT				 = "Cash Paid for Interest"

class ticker(float):
	#inc
	YEAR_INC					= []
	REV						    = []
	SALES_SERV_REV				= []
	OTHER_REV				    = []
	COST_OF_REV					= []
	COGS						= []
	PROFIT					    = []
	OTH_PROFIT				    = []
	OP_EXP					    = []
	SG_AND_ADMIN				= []
	SELL_AND_MARK				= []
	GEN_AND_ADMIN				= []
	R_AND_D					    = []
	DEP_AMORT				    = []
	OTH_OP_EXP				    = []
	OP_INC_LOSS				    = []
	NON_OP_INC_LOSS			    = []
	NET_INT_EXP				    = []
	INT_EXP					    = []
	INT_INC					    = []
	FOREX					    = []
	AFFILIATES				    = []
	NON_OP_INC				    = []
	PRETAX_INCOME			    = []
	INC_TAX_BENEFIT			    = []
	CURR_INC_TAX			    = []
	DEFF_INC_TAX			    = []
	CONT_OPS				    = []
	NET_EXTRA1				    = []
	DISC_OPS				    = []
	ACCT_CHNG				    = []
	INCOME_MI				    = []
	MIN_INTEREST			    = []
	NI_INC  					= []
	PREF_DIVS				    = []
	OTH_ADJ					    = []
	NI_AVAIL_COMMON_GAAP	    = []
	NI_AVAIL_COMMON_ADJ		    = []
	NET_ABNORMAL			    = []
	NET_EXTRA2				    = []
	BASIC_WEIGHT_AVG_SHARES     = []
	DIL_WEIGHT_AVG_SHARES	    = []
	#bal
	YEAR_BAL					= []
	TOTAL_ASSETS1				= []
	CASH_EQ_STI					= []
	CASH_EQ						= []
	STI							= []
	ACCTS_REC					= []
	ACCTS_REC_NET				= []
	NOTES_REC_NET				= []
	INV							= []
	RAW_MAT						= []
	WIP							= []
	FIN_GOODS 					= []
	OTH_INV						= []
	OTH_ST_ASSETS				= []
	DERIV_HEDGE_ASSETS1			= []
	TAXES_RECIEV				= []
	MISC_ST_ASSETS				= []
	TOTAL_CURR_ASSETS			= []
	PPE_NET						= []
	PPE							= []
	ACC_DEPREC					= []
	LTI_RECEIVABLES				= []
	LT_INVEST					= []
	OTH_LT_ASSETS				= []
	TOTAL_INT_ASSETS			= []
	GOODWILL					= []
	OTH_INT_ASSETS				= []
	PREPAID_EXP					= []
	DEFF_TAX_ASSETS				= []
	DERIV_HEDGE_ASSETS2			= []
	MISC_ASSETS					= []
	TOTAL_NON_CURR_ASSETS		= []
	TOTAL_ASSETS2				= []
	LIAB_AND_EQUITY1			= []
	PAYABLES_ACCRUALS			= []
	PAYABLES					= []
	ACCRUED_TAXES				= []
	INT_DIVS_PAYABLES			= []
	OTH_PAYABLES_ACCURALS		= []
	ST_DEBT						= []
	ST_BORROWINGS				= []
	ST_FIN_LEASES				= []
	ST_OP_LEASES				= []
	CURR_LT_DEBT				= []
	OTH_ST_LIAB					= []
	DEFF_REV_1					= []
	DERIV_HEDGE_1				= []
	MISC_ST_LIAB				= []
	TOTAL_CURR_LIAB				= []
	LT_DEBT						= []
	LT_BORROW					= []
	LT_FIN_LEASES				= []
	LT_OP_LEASES				= []
	OTH_LT_LIAB					= []
	ACCURED_LIAB				= []
	PENSION_LIAB				= []
	PENSIONS					= []
	OTH_POST_RET_BEN			= []
	DEFF_REV_2					= []
	DEF_TAX_LIAB				= []
	DERIV_HEDGE_2				= []
	MISC_LT_LIAB				= []
	TOTAL_NON_CURR_LIAB			= []
	TOTAL_LIAB					= []
	PREF_EQUITY_HYBRID_CAP		= []
	SHARE_CAP_APIC				= []
	COMMON_STOCK				= []
	ADD_PAID_CAP				= []
	TREASURY_STOCK				= []
	RE							= []
	OTH_EQUITY					= []
	EQUITY_BEFORE_MIN_INT		= []
	MIN_NON_CONTROL_INT			= []
	TOTAL_EQUITY				= []
	LIAB_AND_EQUITY2			= []
	#cf
	YEAR_CF						= []
	NI_CF  						= []
	DEPRE_AMORT					= []
	NON_CASH_ITEMS				= []
	STOCK_COMP					= []
	DEF_INT_COMP				= []
	OTH_NON_CASH_ADJ			= []
	CHG_NON_CASH_OP				= []
	CHG_ACCTS_REC				= []
	CHG_INVENTORIES				= []
	CHG_ACCTS_PAYABLE			= []
	CHG_OTHER					= []
	NET_CASH_DISC_OPS1			= []
	CASH_OP_ACT					= []
	CASH_INVEST_ACT1			= []
	CHG_FIXED_INTANG			= []
	DISP_FIXED_INTANG			= []
	DISP_FIXED_PROD_ASSETS		= []
	DISP_INTAG_ASSETS			= []
	ACQ_FIXED_INTAG				= []
	ACQ_FIXED_PROD_ASSETS		= []
	ACQ_INTAG_ASSETS			= []
	NET_CHG_LT_INVEST			= []
	DEC_LT_INVEST				= []
	INC_LT_INVEST				= []
	NET_CASH_ACQ_DIV			= []
	CASH_DIVEST					= []
	CASH_ACQ_SUBS				= []
	CASH_JVS					= []
	OTH_INVEST_ACT				= []
	NET_CASH_DISC_OPS2			= []
	CASH_INVEST_ACT2			= []
	CASH_FIN_ACT1				= []
	DIVS_PAID					= []
	CASH_REPAY_DEBT				= []
	CASH_ST_DEBT				= []
	CASH_LT_DEBT				= []
	REPAY_LT_DEBT				= []
	CASH_REPURCH_EQUITY			= []
	INC_CAPITAL_STOCK			= []
	DEC_CAPITAL_STOCK			= []
	OTH_FIN_ACT					= []
	NET_CASH_DISC_OPS3			= []
	CASH_FIN_ACT2				= []
	EFFECT_FOREX_RATES			= []
	NET_CHG_CASH				= []
	CASH_PAID_TAXES				= []
	CASH_PAID_INT				= []