import Calcs
import sys

def instantiateData():
	data = {}
	data['symbol']					= None
	data['YEAR_INC']				= [None] * 35
	data['REV']						= [None] * 35
	data['SALES_SERV_REV']			= [None] * 35
	data['OTHER_REV']				= [None] * 35
	data['COST_OF_REV']				= [None] * 35
	data['COGS']					= [None] * 35
	data['PROFIT']					= [None] * 35
	data['OTH_PROFIT']				= [None] * 35
	data['OP_EXP']					= [None] * 35
	data['SG_AND_ADMIN']			= [None] * 35
	data['SELL_AND_MARK']			= [None] * 35
	data['GEN_AND_ADMIN']			= [None] * 35
	data['R_AND_D']					= [None] * 35
	data['DEP_AMORT']				= [None] * 35
	data['OTH_OP_EXP']				= [None] * 35
	data['OP_INC_LOSS']				= [None] * 35
	data['NON_OP_INC_LOSS']			= [None] * 35
	data['NET_INT_EXP']				= [None] * 35
	data['INT_EXP']					= [None] * 35
	data['INT_INC']					= [None] * 35
	data['FOREX']					= [None] * 35
	data['AFFILIATES']				= [None] * 35
	data['NON_OP_INC']				= [None] * 35
	data['PRETAX_INCOME']			= [None] * 35
	data['INC_TAX_EXPENSE']			= [None] * 35
	data['CURR_INC_TAX']			= [None] * 35
	data['DEFF_INC_TAX']			= [None] * 35
	data['CONT_OPS']				= [None] * 35
	data['NET_EXTRA1']				= [None] * 35
	data['DISC_OPS']				= [None] * 35
	data['ACCT_CHNG']				= [None] * 35
	data['INCOME_MI']				= [None] * 35
	data['MIN_INTEREST']			= [None] * 35
	data['NI_INC']  				= [None] * 35
	data['PREF_DIVS']				= [None] * 35
	data['OTH_ADJ']					= [None] * 35
	data['NI_AVAIL_COMMON_GAAP']	= [None] * 35
	data['NI_AVAIL_COMMON_ADJ']		= [None] * 35
	data['NET_ABNORMAL']			= [None] * 35
	data['NET_EXTRA2']				= [None] * 35
	data['BASIC_WEIGHT_AVG_SHARES'] = [None] * 35
	data['DIL_WEIGHT_AVG_SHARES']	= [None] * 35
	data['YEAR_BAL']				= [None] * 35
	data['TOTAL_ASSETS1']			= [None] * 35
	data['CASH_EQ_STI']				= [None] * 35
	data['CASH_EQ']					= [None] * 35
	data['ST_INVEST']				= [None] * 35
	data['ACCTS_REC']				= [None] * 35
	data['ACCTS_REC_NET']			= [None] * 35
	data['NOTES_REC_NET']			= [None] * 35
	data['INV']						= [None] * 35
	data['RAW_MAT']					= [None] * 35
	data['WIP']						= [None] * 35
	data['FIN_GOODS'] 				= [None] * 35
	data['OTH_INV']					= [None] * 35
	data['OTH_ST_ASSETS']			= [None] * 35
	data['DERIV_HEDGE_ASSETS1']		= [None] * 35
	data['TAXES_RECIEV']			= [None] * 35
	data['MISC_ST_ASSETS']			= [None] * 35
	data['TOTAL_CURR_ASSETS']		= [None] * 35
	data['PPE_NET']					= [None] * 35
	data['PPE']						= [None] * 35
	data['ACC_DEPREC']				= [None] * 35
	data['LTI_RECEIVABLES']			= [None] * 35
	data['LT_INVEST']				= [None] * 35
	data['OTH_LT_ASSETS']			= [None] * 35
	data['TOTAL_INTANG_ASSETS']		= [None] * 35
	data['GOODWILL']				= [None] * 35
	data['OTH_INTANG_ASSETS']		= [None] * 35
	data['PREPAID_EXP']				= [None] * 35
	data['DEFF_TAX_ASSETS']			= [None] * 35
	data['DERIV_HEDGE_ASSETS2']		= [None] * 35
	data['MISC_ASSETS']				= [None] * 35
	data['TOTAL_NON_CURR_ASSETS']	= [None] * 35
	data['TOTAL_ASSETS2']			= [None] * 35
	data['LIAB_AND_EQUITY1']		= [None] * 35
	data['PAYABLES_ACCRUALS']		= [None] * 35
	data['PAYABLES']				= [None] * 35
	data['ACCRUED_TAXES']			= [None] * 35
	data['INT_DIVS_PAYABLES']		= [None] * 35
	data['OTH_PAYABLES_ACCURALS']	= [None] * 35
	data['ST_DEBT']					= [None] * 35
	data['ST_BORROWINGS']			= [None] * 35
	data['ST_FIN_LEASES']			= [None] * 35
	data['ST_OP_LEASES']			= [None] * 35
	data['CURR_LT_DEBT']			= [None] * 35
	data['OTH_ST_LIAB']				= [None] * 35
	data['DEFF_REV_1']				= [None] * 35
	data['DERIV_HEDGE_1']			= [None] * 35
	data['MISC_ST_LIAB']			= [None] * 35
	data['TOTAL_CURR_LIAB']			= [None] * 35
	data['LT_DEBT']					= [None] * 35
	data['LT_BORROW']				= [None] * 35
	data['LT_FIN_LEASES']			= [None] * 35
	data['LT_OP_LEASES']			= [None] * 35
	data['OTH_LT_LIAB']				= [None] * 35
	data['ACCURED_LIAB']			= [None] * 35
	data['PENSION_LIAB']			= [None] * 35
	data['PENSIONS']				= [None] * 35
	data['OTH_POST_RET_BEN']		= [None] * 35
	data['DEFF_REV_2']				= [None] * 35
	data['DEF_TAX_LIAB']			= [None] * 35
	data['DERIV_HEDGE_2']			= [None] * 35
	data['MISC_LT_LIAB']			= [None] * 35
	data['TOTAL_NON_CURR_LIAB']		= [None] * 35
	data['TOTAL_LIAB']				= [None] * 35
	data['PREF_EQUITY_HYBRID_CAP']	= [None] * 35
	data['SHARE_CAP_APIC']			= [None] * 35
	data['COMMON_STOCK']			= [None] * 35
	data['ADD_PAID_CAP']			= [None] * 35
	data['TREASURY_STOCK']			= [None] * 35
	data['RE']						= [None] * 35
	data['OTH_EQUITY']				= [None] * 35
	data['EQUITY_BEFORE_MIN_INT']	= [None] * 35
	data['MIN_NON_CONTROL_INT']		= [None] * 35
	data['TOTAL_EQUITY']			= [None] * 35
	data['LIAB_AND_EQUITY']			= [None] * 35
	data['YEAR_CF']					= [None] * 35
	data['NI_CF']  					= [None] * 35
	data['DEPRE_AMORT']				= [None] * 35
	data['NON_CASH_ITEMS']			= [None] * 35
	data['STOCK_COMP']				= [None] * 35
	data['DEF_INT_COMP']			= [None] * 35
	data['OTH_NON_CASH_ADJ']		= [None] * 35
	data['CHG_NON_CASH_OP']			= [None] * 35
	data['CREDIT_SALES']			= [None] * 35
	data['CHG_INVENTORIES']			= [None] * 35
	data['CHG_ACCTS_PAYABLE']		= [None] * 35
	data['CHG_OTHER']				= [None] * 35
	data['NET_CASH_DISC_OPS1']		= [None] * 35
	data['CASH_OP_ACT']				= [None] * 35
	data['CASH_INVEST_ACT1']		= [None] * 35
	data['CHG_FIXED_INTANG']		= [None] * 35
	data['DISP_FIXED_INTANG']		= [None] * 35
	data['DISP_FIXED_PROD_ASSETS']	= [None] * 35
	data['DISP_INTANG_ASSETS']		= [None] * 35
	data['ACQ_FIXED_INTANG']		= [None] * 35
	data['ACQ_FIXED_PROD_ASSETS']	= [None] * 35
	data['ACQ_INTANG_ASSETS']		= [None] * 35
	data['NET_CHG_LT_INVEST']		= [None] * 35
	data['DEC_LT_INVEST']			= [None] * 35
	data['INC_LT_INVEST']			= [None] * 35
	data['NET_CASH_ACQ_DIV']		= [None] * 35
	data['CASH_DIVEST']				= [None] * 35
	data['CASH_ACQ_SUBS']			= [None] * 35
	data['CASH_JVS']				= [None] * 35
	data['OTH_INVEST_ACT']			= [None] * 35
	data['NET_CASH_DISC_OPS2']		= [None] * 35
	data['CASH_INVEST']				= [None] * 35
	data['CASH_FIN_ACT1']			= [None] * 35
	data['DIVS_PAID']				= [None] * 35
	data['CASH_REPAY_DEBT']			= [None] * 35
	data['CASH_ST_DEBT']			= [None] * 35
	data['CASH_LT_DEBT']			= [None] * 35
	data['REPAY_LT_DEBT']			= [None] * 35
	data['CASH_REPURCH_EQUITY']		= [None] * 35
	data['INC_CAPITAL_STOCK']		= [None] * 35
	data['DEC_CAPITAL_STOCK']		= [None] * 35
	data['OTH_FIN_ACT']				= [None] * 35
	data['NET_CASH_DISC_OPS3']		= [None] * 35
	data['CASH_FIN_ACT2']			= [None] * 35
	data['EFFECT_FOREX_RATES']		= [None] * 35
	data['NET_CHG_CASH']			= [None] * 35
	data['CASH_PAID_TAXES']			= [None] * 35
	data['CASH_PAID_INT']			= [None] * 35

	return data
	
def instantiateDataCalc():
	dataCalc = {}
	dataCalc['symbol']							= [0]
	dataCalc['YEAR_INC'] 						= [0] * 35
	dataCalc['YEAR_BAL']						= [0] * 35
	dataCalc['YEAR_CF']							= [0] * 35
	dataCalc['PRICE']							= [0] * 35
	dataCalc['AVG_NI_3YEAR']					= [0] * 35
	dataCalc['AVG_EBIT_3YEAR']					= [0] * 35
	dataCalc['AVG_LEV_FCF_3YEAR']				= [0] * 35
	dataCalc['MARGINAL_TAX_RATE']				= [0] * 35
	dataCalc['FAIR_RETURN_RATE']				= [0] * 35
	dataCalc['NO_GROWTH_PE']					= [0] * 35
	dataCalc['REQUIRED_RETURN']					= [0] * 35
	dataCalc['AAA_BOND_YIELD']					= [0] * 35
	dataCalc['GROWTH_MULTIPLE']					= [0] * 35
	dataCalc['REV_GROWTH_RATE']					= [0] * 35
	dataCalc['EBITDA_GROWTH_RATE']				= [0] * 35
	dataCalc['EBIT_GROWTH_RATE']				= [0] * 35
	dataCalc['NI_GROWTH_RATE']					= [0] * 35
	dataCalc['EPS_GROWTH_RATE']					= [0] * 35
	dataCalc['GROWTH_RATE'] 					= [0] * 35
	dataCalc['AVG_3YEARS'] 						= [0] * 35
	dataCalc['AVG_5YEARS'] 						= [0] * 35
	dataCalc['COST_OF_SALES']					= [0] * 35
	dataCalc['WORKING_CAPITAL'] 				= [0] * 35
	dataCalc['CAPITAL_EMPLOYED'] 				= [0] * 35
	dataCalc['TOTAL_INVEST']					= [0] * 35
	dataCalc['TOTAL_DEBT']						= [0] * 35
	dataCalc['EBITDA']							= [0] * 35
	dataCalc['EBIAT']							= [0] * 35
	dataCalc['EBIT']							= [0] * 35
	dataCalc['CAPEX'] 							= [0] * 35
	dataCalc['LEV_FCF']							= [0] * 35
	dataCalc['UN_LEV_FCF']						= [0] * 35
	dataCalc['AVG_RECEIVABLES'] 				= [0] * 35
	dataCalc['AVG_PAYABLES_ACCRUALS'] 			= [0] * 35
	dataCalc['AVG_WORKING_CAPITAL'] 			= [0] * 35
	dataCalc['AVG_INVENTORY']					= [0] * 35
	dataCalc['AVG_INVEST'] 						= [0] * 35
	dataCalc['AVG_LT_ASSETS'] 					= [0] * 35
	dataCalc['AVG_ASSETS'] 						= [0] * 35
	dataCalc['AVG_LIABILITIES']					= [0] * 35
	dataCalc['AVG_EQUITY'] 						= [0] * 35
	dataCalc['AVG_DEBT'] 						= [0] * 35
	dataCalc['CASH_RATIO']						= [0] * 35
	dataCalc['CASH_STI_RATIO']					= [0] * 35
	dataCalc['CASH_SERVICE_RATIO']				= [0] * 35
	dataCalc['INT_SERVICE_RATIO']				= [0] * 35
	dataCalc['CASH_ST_DEBT_RATIO'] 				= [0] * 35
	dataCalc['ACID_TEST']						= [0] * 35
	dataCalc['QUICK_RATIO']						= [0] * 35
	dataCalc['QUICK_RATIO_2']					= [0] * 35
	dataCalc['CURRENT_RATIO']					= [0] * 35
	dataCalc['NWC_TO_TA']						= [0] * 35
	dataCalc['DEBT_SERVICE_RATIO'] 				= [0] * 35
	dataCalc['CHG_ST_DEBT']						= [0] * 35
	dataCalc['CHG_LT_DEBT']						= [0] * 35
	dataCalc['CHG_NET_DEBT']					= [0] * 35
	dataCalc['NET_DEBT'] 						= [0] * 35
	dataCalc['DEBT_RATIO'] 						= [0] * 35
	dataCalc['TOTAL_CURR_LIAB_RATIO'] 			= [0] * 35
	dataCalc['LT_DEBT_RATIO'] 					= [0] * 35
	dataCalc['DEBT_EQ_RATIO'] 					= [0] * 35
	dataCalc['DEBT_TO_EBIT'] 					= [0] * 35
	dataCalc['FIXED_CHARGE_COVERAGE'] 			= [0] * 35
	dataCalc['DEGREE_COMBINED_LEV'] 			= [0] * 35
	dataCalc['DEGREE_OPERATING_LEV']			= [0] * 35
	dataCalc['DEGREE_FINANCIAL_LEV']			= [0] * 35
	dataCalc['DFL_RATIO'] 						= [0] * 35
	dataCalc['FINANCIAL_LEVERAGE'] 				= [0] * 35
	dataCalc['EQUITY_RATIO'] 					= [0] * 35
	dataCalc['EQUITY_MULTIPLIER_RATIO_1'] 		= [0] * 35
	dataCalc['EQUITY_MULTIPLIER_RATIO_2'] 		= [0] * 35
	dataCalc['NAV'] 							= [0] * 35
	dataCalc['EFFECTIVE_INT_RATE'] 				= [0] * 35
	dataCalc['DEBT_COST_CAP']					= [0] * 35
	dataCalc['WACC']							= [0] * 35
	dataCalc['SALES_TURNOVER'] 					= [0] * 35
	dataCalc['DSO'] 							= [0] * 35
	dataCalc['ASSET_TURNOVER']					= [0] * 35
	dataCalc['ASSET_TURN_RATE']					= [0] * 35
	dataCalc['LT_ASSET_TURNOVER']				= [0] * 35
	dataCalc['LT_ASSET_TURN_RATE']				= [0] * 35
	dataCalc['INV_SALES_TURNOVER']				= [0] * 35
	dataCalc['DSI']								= [0] * 35
	dataCalc['INV_COGS_TURNOVER']				= [0] * 35
	dataCalc['DIO']								= [0] * 35
	dataCalc['RECEIVABLES_ACCTS_TURNOVER']		= [0] * 35
	dataCalc['DRO']								= [0] * 35
	dataCalc['WORKING_CAP_TURNOVER']			= [0] * 35
	dataCalc['DWC']								= [0] * 35
	dataCalc['ROI_INVESTMENTS']					= [0] * 35
	dataCalc['CREDITORS_TURNOVER']				= [0] * 35
	dataCalc['CDO']								= [0] * 35
	dataCalc['PAYABLES_TURNOVER_COGS']			= [0] * 35
	dataCalc['DPO_COGS']						= [0] * 35
	dataCalc['PAYABLES_TURNOVER_COS']			= [0] * 35
	dataCalc['DPO_COS']							= [0] * 35
	dataCalc['LIAB_TURNOVER']					= [0] * 35
	dataCalc['LIAB_TURN_RATE']					= [0] * 35
	dataCalc['CHG_DEBT_REPAYMENT_REQ']			= [0] * 35
	dataCalc['DEBTORS_PAYBACK_PERIOD']			= [0] * 35
	dataCalc['BURN_RATE']						= [0] * 35
	dataCalc['CCC']								= [0] * 35
	dataCalc['ROS']								= [0] * 35
	dataCalc['ROE']								= [0] * 35
	dataCalc['ROA']								= [0] * 35
	dataCalc['ROCE_NI']							= [0] * 35
	dataCalc['EPS_DILUTED_NI']					= [0] * 35
	dataCalc['EPS_DILUTED_EBIT']				= [0] * 35
	dataCalc['ROCE_EBIT']						= [0] * 35
	dataCalc['PE']								= [0] * 35
	dataCalc['PE_REL_3']						= [0] * 35
	dataCalc['PE_REL_5']						= [0] * 35
	dataCalc['EARNINGS_POWER']					= [0] * 35
	dataCalc['GROSS_MARGIN']					= [0] * 35
	dataCalc['NOPAT_NI']						= [0] * 35
	dataCalc['NOPAT_EBIT']						= [0] * 35
	dataCalc['ROIC']							= [0] * 35
	dataCalc['OPERATING_RATIO']					= [0] * 35
	dataCalc['OP_PROFIT_MARGIN']				= [0] * 35
	dataCalc['MV']								= [0] * 35
	dataCalc['MV_EBIT_RATIO']					= [0] * 35
	dataCalc['ORIG_GRAHAM']						= [0] * 35
	dataCalc['REVISED_GRAHAM']					= [0] * 35
	dataCalc['EV']								= [0] * 35
	dataCalc['EV_EBIT']							= [0] * 35
	dataCalc['EV_NI']							= [0] * 35
	dataCalc['BV']								= [0] * 35
	dataCalc['BV_PER_SHARE']					= [0] * 35
	dataCalc['BV_NI']							= [0] * 35
	dataCalc['BV_EBIT']							= [0] * 35
	dataCalc['PRICE_SALES']						= [0] * 35
	dataCalc['PRICE_BOOK']						= [0] * 35
	dataCalc['PRICE_NAV']						= [0] * 35
	dataCalc['PRICE_FCF']						= [0] * 35
	dataCalc['PRICE_UN_FCF']					= [0] * 35
	dataCalc['MV_OCF']							= [0] * 35
	dataCalc['CASH_PRICE_RATIO']				= [0] * 35
	dataCalc['INTRINSIC_VALUE_NI']				= [0] * 35
	dataCalc['INTRINSIC_VALUE_EBIT']			= [0] * 35
	dataCalc['INTRINSIC_VALUE_FCF']				= [0] * 35
	dataCalc['MARGIN_OF_SAFETY_NI']				= [0] * 35
	dataCalc['MARGIN_OF_SAFETY_EBIT']			= [0] * 35
	dataCalc['MARGIN_OF_SAFETY_FCF']			= [0] * 35
	dataCalc['DUPONT_SYSTEM_1']					= [0] * 35
	dataCalc['DUPONT_SYSTEM_2']					= [0] * 35
	dataCalc['RETENTION_RATIO']					= [0] * 35
	dataCalc['DIV_PAYOUT_RATIO']				= [0] * 35
	dataCalc['EARNINGS_YIELD']					= [0] * 35
	dataCalc['DIVS_YIELD']						= [0] * 35
	dataCalc['SGR']								= [0] * 35

	dataCalc['YEAR_INC']						= [None] * 35
	dataCalc['YEAR_BAL']						= [None] * 35
	dataCalc['YEAR_CF'] 						= [None] * 35
	dataCalc['PRICE']							= [None] * 35
	dataCalc['AVG_NI_3YEAR']					= [None] * 35
	dataCalc['AVG_EBIT_3YEAR']					= [None] * 35
	dataCalc['AVG_LEV_FCF_3YEAR']				= [None] * 35
	dataCalc['MARGINAL_TAX_RATE']				= [None] * 35
	dataCalc['FAIR_RETURN_RATE']				= [None] * 35
	dataCalc['NO_GROWTH_PE']					= [None] * 35
	dataCalc['REQUIRED_RETURN']					= [None] * 35
	dataCalc['AAA_BOND_YIELD']					= [None] * 35
	dataCalc['GROWTH_MULTIPLE']					= [None] * 35
	dataCalc['REV_GROWTH_RATE']					= [None] * 35
	dataCalc['EBITDA_GROWTH_RATE']				= [None] * 35
	dataCalc['EBIT_GROWTH_RATE']				= [None] * 35
	dataCalc['NI_GROWTH_RATE']					= [None] * 35
	dataCalc['EPS_GROWTH_RATE']					= [None] * 35
	dataCalc['GROWTH_RATE'] 					= [None] * 35
	dataCalc['AVG_3YEARS'] 						= [None] * 35
	dataCalc['AVG_5YEARS'] 						= [None] * 35
	dataCalc['COST_OF_SALES']					= [None] * 35
	dataCalc['WORKING_CAPITAL'] 				= [None] * 35
	dataCalc['CAPITAL_EMPLOYED'] 				= [None] * 35
	dataCalc['TOTAL_INVEST']					= [None] * 35
	dataCalc['TOTAL_DEBT']						= [None] * 35
	dataCalc['EBITDA']							= [None] * 35
	dataCalc['EBIAT']							= [None] * 35
	dataCalc['EBIT']							= [None] * 35
	dataCalc['CAPEX'] 							= [None] * 35
	dataCalc['LEV_FCF']							= [None] * 35
	dataCalc['UN_LEV_FCF']						= [None] * 35
	dataCalc['AVG_RECEIVABLES'] 				= [None] * 35
	dataCalc['AVG_PAYABLES_ACCRUALS'] 			= [None] * 35
	dataCalc['AVG_WORKING_CAPITAL'] 			= [None] * 35
	dataCalc['AVG_INVENTORY']					= [None] * 35
	dataCalc['AVG_INVEST'] 						= [None] * 35
	dataCalc['AVG_LT_ASSETS'] 					= [None] * 35
	dataCalc['AVG_ASSETS'] 						= [None] * 35
	dataCalc['AVG_LIABILITIES']					= [None] * 35
	dataCalc['AVG_EQUITY'] 						= [None] * 35
	dataCalc['AVG_DEBT'] 						= [None] * 35
	dataCalc['CASH_RATIO']						= [None] * 35
	dataCalc['CASH_STI_RATIO']					= [None] * 35
	dataCalc['CASH_SERVICE_RATIO']				= [None] * 35
	dataCalc['INT_SERVICE_RATIO']				= [None] * 35
	dataCalc['CASH_ST_DEBT_RATIO'] 				= [None] * 35
	dataCalc['ACID_TEST']						= [None] * 35
	dataCalc['QUICK_RATIO']						= [None] * 35
	dataCalc['QUICK_RATIO_2']					= [None] * 35
	dataCalc['CURRENT_RATIO']					= [None] * 35
	dataCalc['NWC_TO_TA']						= [None] * 35
	dataCalc['DEBT_SERVICE_RATIO'] 				= [None] * 35
	dataCalc['CHG_ST_DEBT']						= [None] * 35
	dataCalc['CHG_LT_DEBT']						= [None] * 35
	dataCalc['CHG_NET_DEBT']					= [None] * 35
	dataCalc['NET_DEBT'] 						= [None] * 35
	dataCalc['DEBT_RATIO'] 						= [None] * 35
	dataCalc['TOTAL_CURR_LIAB_RATIO'] 			= [None] * 35
	dataCalc['LT_DEBT_RATIO'] 					= [None] * 35
	dataCalc['DEBT_EQ_RATIO'] 					= [None] * 35
	dataCalc['DEBT_TO_EBIT'] 					= [None] * 35
	dataCalc['FIXED_CHARGE_COVERAGE'] 			= [None] * 35
	dataCalc['DEGREE_COMBINED_LEV'] 			= [None] * 35
	dataCalc['DEGREE_OPERATING_LEV']			= [None] * 35
	dataCalc['DEGREE_FINANCIAL_LEV']			= [None] * 35
	dataCalc['DFL_RATIO'] 						= [None] * 35
	dataCalc['FINANCIAL_LEVERAGE'] 				= [None] * 35
	dataCalc['EQUITY_RATIO'] 					= [None] * 35
	dataCalc['EQUITY_MULTIPLIER_RATIO_1'] 		= [None] * 35
	dataCalc['EQUITY_MULTIPLIER_RATIO_2'] 		= [None] * 35
	dataCalc['NAV'] 							= [None] * 35
	dataCalc['EFFECTIVE_INT_RATE'] 				= [None] * 35
	dataCalc['DEBT_COST_CAP']					= [None] * 35
	dataCalc['WACC']							= [None] * 35
	dataCalc['SALES_TURNOVER'] 					= [None] * 35
	dataCalc['DSO'] 							= [None] * 35
	dataCalc['ASSET_TURNOVER']					= [None] * 35
	dataCalc['ASSET_TURN_RATE']					= [None] * 35
	dataCalc['LT_ASSET_TURNOVER']				= [None] * 35
	dataCalc['LT_ASSET_TURN_RATE']				= [None] * 35
	dataCalc['INV_SALES_TURNOVER']				= [None] * 35
	dataCalc['DSI']								= [None] * 35
	dataCalc['INV_COGS_TURNOVER']				= [None] * 35
	dataCalc['DIO']								= [None] * 35
	dataCalc['RECEIVABLES_ACCTS_TURNOVER']		= [None] * 35
	dataCalc['DRO']								= [None] * 35
	dataCalc['WORKING_CAP_TURNOVER']			= [None] * 35
	dataCalc['DWC']								= [None] * 35
	dataCalc['ROI_INVESTMENTS']					= [None] * 35
	dataCalc['CREDITORS_TURNOVER']				= [None] * 35
	dataCalc['CDO']								= [None] * 35
	dataCalc['PAYABLES_TURNOVER_COGS']			= [None] * 35
	dataCalc['DPO_COGS']						= [None] * 35
	dataCalc['PAYABLES_TURNOVER_COS']			= [None] * 35
	dataCalc['DPO_COS']							= [None] * 35
	dataCalc['LIAB_TURNOVER']					= [None] * 35
	dataCalc['LIAB_TURN_RATE']					= [None] * 35
	dataCalc['CHG_DEBT_REPAYMENT_REQ']			= [None] * 35
	dataCalc['DEBTORS_PAYBACK_PERIOD']			= [None] * 35
	dataCalc['BURN_RATE']						= [None] * 35
	dataCalc['CCC']								= [None] * 35
	dataCalc['ROS']								= [None] * 35
	dataCalc['ROE']								= [None] * 35
	dataCalc['ROA']								= [None] * 35
	dataCalc['ROCE_NI']							= [None] * 35
	dataCalc['EPS_DILUTED_NI']					= [None] * 35
	dataCalc['EPS_DILUTED_EBIT']				= [None] * 35
	dataCalc['ROCE_EBIT']						= [None] * 35
	dataCalc['PE']								= [None] * 35
	dataCalc['PE_REL_3']						= [None] * 35
	dataCalc['PE_REL_5']						= [None] * 35
	dataCalc['EARNINGS_POWER']					= [None] * 35
	dataCalc['GROSS_MARGIN']					= [None] * 35
	dataCalc['NOPAT_NI']						= [None] * 35
	dataCalc['NOPAT_EBIT']						= [None] * 35
	dataCalc['ROIC']							= [None] * 35
	dataCalc['OPERATING_RATIO']					= [None] * 35
	dataCalc['OP_PROFIT_MARGIN']				= [None] * 35
	dataCalc['MV']								= [None] * 35
	dataCalc['MV_EBIT_RATIO']					= [None] * 35
	dataCalc['ORIG_GRAHAM']						= [None] * 35
	dataCalc['REVISED_GRAHAM']					= [None] * 35
	dataCalc['EV']								= [None] * 35
	dataCalc['EV_EBIT']							= [None] * 35
	dataCalc['EV_NI']							= [None] * 35
	dataCalc['BV']								= [None] * 35
	dataCalc['BV_PER_SHARE']					= [None] * 35
	dataCalc['BV_NI']							= [None] * 35
	dataCalc['BV_EBIT']							= [None] * 35
	dataCalc['PRICE_SALES']						= [None] * 35
	dataCalc['PRICE_BOOK']						= [None] * 35
	dataCalc['PRICE_NAV']						= [None] * 35
	dataCalc['PRICE_FCF']						= [None] * 35
	dataCalc['PRICE_UN_FCF']					= [None] * 35
	dataCalc['MV_OCF']							= [None] * 35
	dataCalc['CASH_PRICE_RATIO']				= [None] * 35
	dataCalc['INTRINSIC_VALUE_NI']				= [None] * 35
	dataCalc['INTRINSIC_VALUE_EBIT']			= [None] * 35
	dataCalc['INTRINSIC_VALUE_FCF']				= [None] * 35
	dataCalc['MARGIN_OF_SAFETY_NI']				= [None] * 35
	dataCalc['MARGIN_OF_SAFETY_EBIT']			= [None] * 35
	dataCalc['MARGIN_OF_SAFETY_FCF']			= [None] * 35
	dataCalc['DUPONT_SYSTEM_1']					= [None] * 35
	dataCalc['DUPONT_SYSTEM_2']					= [None] * 35
	dataCalc['RETENTION_RATIO']					= [None] * 35
	dataCalc['DIV_PAYOUT_RATIO']				= [None] * 35
	dataCalc['EARNINGS_YIELD']					= [None] * 35
	dataCalc['DIVS_YIELD']						= [None] * 35
	dataCalc['SGR']								= [None] * 35

	dataCalc['YEAR_INC']						= Calcs.Names.YEAR_INC
	dataCalc['YEAR_BAL']						= Calcs.Names.YEAR_BAL
	dataCalc['YEAR_CF']							= Calcs.Names.YEAR_CF
	dataCalc['MARGINAL_TAX_RATE'][0]			= Calcs.Names.MARGINAL_TAX_RATE
	dataCalc['FAIR_RETURN_RATE'][0]				= Calcs.Names.FAIR_RETURN_RATE
	dataCalc['NO_GROWTH_PE'][0]					= Calcs.Names.NO_GROWTH_PE
	dataCalc['REQUIRED_RETURN'][0]				= Calcs.Names.REQUIRED_RETURN
	dataCalc['AAA_BOND_YIELD'][0]				= Calcs.Names.AAA_BOND_YIELD
	dataCalc['GROWTH_MULTIPLE'][0]				= Calcs.Names.GROWTH_MULTIPLE
	dataCalc['REV_GROWTH_RATE'][0]				= Calcs.Names.REV_GROWTH_RATE
	dataCalc['EBITDA_GROWTH_RATE'][0]			= Calcs.Names.EBITDA_GROWTH_RATE
	dataCalc['EBIT_GROWTH_RATE'][0]				= Calcs.Names.EBIT_GROWTH_RATE
	dataCalc['NI_GROWTH_RATE'][0]				= Calcs.Names.NI_GROWTH_RATE
	dataCalc['EPS_GROWTH_RATE'][0]				= Calcs.Names.EPS_GROWTH_RATE
	dataCalc['GROWTH_RATE'][0]					= Calcs.Names.GROWTH_RATE
	dataCalc['AVG_3YEARS'][0]					= Calcs.Names.AVG_3YEARS
	dataCalc['AVG_5YEARS'][0]					= Calcs.Names.AVG_5YEARS
	dataCalc['COST_OF_SALES'][0]				= Calcs.Names.COST_OF_SALES
	dataCalc['WORKING_CAPITAL'][0]				= Calcs.Names.WORKING_CAPITAL
	dataCalc['CAPITAL_EMPLOYED'][0]				= Calcs.Names.CAPITAL_EMPLOYED
	dataCalc['TOTAL_INVEST'][0]					= Calcs.Names.TOTAL_INVEST
	dataCalc['TOTAL_DEBT'][0]					= Calcs.Names.TOTAL_DEBT
	dataCalc['EBITDA'][0]						= Calcs.Names.EBITDA
	dataCalc['EBIAT'][0]						= Calcs.Names.EBIAT
	dataCalc['EBIT'][0]							= Calcs.Names.EBIT
	dataCalc['CAPEX'][0]						= Calcs.Names.CAPEX
	dataCalc['LEV_FCF'][0]						= Calcs.Names.LEV_FCF
	dataCalc['UN_LEV_FCF'][0]					= Calcs.Names.UN_LEV_FCF
	dataCalc['AVG_NI_3YEAR'][0]					= Calcs.Names.AVG_NI_3YEAR
	dataCalc['AVG_EBIT_3YEAR'][0]				= Calcs.Names.AVG_EBIT_3YEAR
	dataCalc['AVG_LEV_FCF_3YEAR'][0]			= Calcs.Names.AVG_LEV_FCF_3YEAR
	dataCalc['AVG_RECEIVABLES'][0]				= Calcs.Names.AVG_RECEIVABLES
	dataCalc['AVG_PAYABLES_ACCRUALS'][0]		= Calcs.Names.AVG_PAYABLES_ACCRUALS
	dataCalc['AVG_WORKING_CAPITAL'][0]			= Calcs.Names.AVG_WORKING_CAPITAL
	dataCalc['AVG_INVENTORY'][0]				= Calcs.Names.AVG_INVENTORY
	dataCalc['AVG_INVEST'][0]					= Calcs.Names.AVG_INVEST
	dataCalc['AVG_LT_ASSETS'][0]				= Calcs.Names.AVG_LT_ASSETS
	dataCalc['AVG_ASSETS'][0]					= Calcs.Names.AVG_ASSETS
	dataCalc['AVG_LIABILITIES'][0]				= Calcs.Names.AVG_LIABILITIES
	dataCalc['AVG_EQUITY'][0]					= Calcs.Names.AVG_EQUITY
	dataCalc['AVG_DEBT'][0]						= Calcs.Names.AVG_DEBT
	dataCalc['CASH_RATIO'][0]					= Calcs.Names.CASH_RATIO
	dataCalc['CASH_STI_RATIO'][0]				= Calcs.Names.CASH_STI_RATIO
	dataCalc['CASH_SERVICE_RATIO'][0]			= Calcs.Names.CASH_SERVICE_RATIO
	dataCalc['INT_SERVICE_RATIO'][0]			= Calcs.Names.INT_SERVICE_RATIO
	dataCalc['CASH_ST_DEBT_RATIO'][0]			= Calcs.Names.CASH_ST_DEBT_RATIO
	dataCalc['ACID_TEST'][0]					= Calcs.Names.ACID_TEST
	dataCalc['QUICK_RATIO'][0]					= Calcs.Names.QUICK_RATIO
	dataCalc['QUICK_RATIO_2'][0]				= Calcs.Names.QUICK_RATIO_2
	dataCalc['CURRENT_RATIO'][0]				= Calcs.Names.CURRENT_RATIO
	dataCalc['NWC_TO_TA'][0]					= Calcs.Names.NWC_TO_TA
	dataCalc['DEBT_SERVICE_RATIO'][0]			= Calcs.Names.DEBT_SERVICE_RATIO
	dataCalc['CHG_ST_DEBT'][0]					= Calcs.Names.CHG_ST_DEBT
	dataCalc['CHG_LT_DEBT'][0]					= Calcs.Names.CHG_LT_DEBT
	dataCalc['CHG_NET_DEBT'][0]					= Calcs.Names.CHG_NET_DEBT
	dataCalc['NET_DEBT'][0]						= Calcs.Names.NET_DEBT
	dataCalc['DEBT_RATIO'][0]					= Calcs.Names.DEBT_RATIO
	dataCalc['TOTAL_CURR_LIAB_RATIO'][0]		= Calcs.Names.TOTAL_CURR_LIAB_RATIO
	dataCalc['LT_DEBT_RATIO'][0]				= Calcs.Names.LT_DEBT_RATIO
	dataCalc['DEBT_EQ_RATIO'][0]				= Calcs.Names.DEBT_EQ_RATIO
	dataCalc['DEBT_TO_EBIT'][0]					= Calcs.Names.DEBT_TO_EBIT
	dataCalc['FIXED_CHARGE_COVERAGE'][0]		= Calcs.Names.FIXED_CHARGE_COVERAGE
	dataCalc['DEGREE_COMBINED_LEV'][0]			= Calcs.Names.DEGREE_COMBINED_LEV
	dataCalc['DEGREE_OPERATING_LEV'][0]			= Calcs.Names.DEGREE_OPERATING_LEV
	dataCalc['DEGREE_FINANCIAL_LEV'][0]			= Calcs.Names.DEGREE_FINANCIAL_LEV
	dataCalc['DFL_RATIO'][0]					= Calcs.Names.DFL_RATIO
	dataCalc['FINANCIAL_LEVERAGE'][0]			= Calcs.Names.FINANCIAL_LEVERAGE
	dataCalc['EQUITY_RATIO'][0]					= Calcs.Names.EQUITY_RATIO
	dataCalc['EQUITY_MULTIPLIER_RATIO_1'][0]	= Calcs.Names.EQUITY_MULTIPLIER_RATIO_1
	dataCalc['EQUITY_MULTIPLIER_RATIO_2'][0]	= Calcs.Names.EQUITY_MULTIPLIER_RATIO_2
	dataCalc['NAV'][0]							= Calcs.Names.NAV
	dataCalc['EFFECTIVE_INT_RATE'][0]			= Calcs.Names.EFFECTIVE_INT_RATE
	dataCalc['DEBT_COST_CAP'][0]				= Calcs.Names.DEBT_COST_CAP
	dataCalc['WACC'][0]							= Calcs.Names.WACC
	dataCalc['SALES_TURNOVER'][0]				= Calcs.Names.SALES_TURNOVER
	dataCalc['DSO'][0]							= Calcs.Names.DSO
	dataCalc['ASSET_TURNOVER'][0]				= Calcs.Names.ASSET_TURNOVER
	dataCalc['ASSET_TURN_RATE'][0]				= Calcs.Names.ASSET_TURN_RATE
	dataCalc['LT_ASSET_TURNOVER'][0]			= Calcs.Names.LT_ASSET_TURNOVER
	dataCalc['LT_ASSET_TURN_RATE'][0]			= Calcs.Names.LT_ASSET_TURN_RATE
	dataCalc['INV_SALES_TURNOVER'][0]			= Calcs.Names.INV_SALES_TURNOVER
	dataCalc['DSI'][0]							= Calcs.Names.DSI
	dataCalc['INV_COGS_TURNOVER'][0]			= Calcs.Names.INV_COGS_TURNOVER
	dataCalc['DIO'][0]							= Calcs.Names.DIO
	dataCalc['RECEIVABLES_ACCTS_TURNOVER'][0]	= Calcs.Names.RECEIVABLES_ACCTS_TURNOVER
	dataCalc['DRO'][0]							= Calcs.Names.DRO
	dataCalc['WORKING_CAP_TURNOVER'][0]			= Calcs.Names.WORKING_CAP_TURNOVER
	dataCalc['DWC'][0]							= Calcs.Names.DWC
	dataCalc['ROI_INVESTMENTS'][0]				= Calcs.Names.ROI_INVESTMENTS
	dataCalc['CREDITORS_TURNOVER'][0]			= Calcs.Names.CREDITORS_TURNOVER
	dataCalc['CDO'][0]							= Calcs.Names.CDO
	dataCalc['PAYABLES_TURNOVER_COGS'][0]		= Calcs.Names.PAYABLES_TURNOVER_COGS
	dataCalc['DPO_COGS'][0]						= Calcs.Names.DPO_COGS
	dataCalc['PAYABLES_TURNOVER_COS'][0]		= Calcs.Names.PAYABLES_TURNOVER_COS
	dataCalc['DPO_COS'][0]						= Calcs.Names.DPO_COS
	dataCalc['LIAB_TURNOVER'][0]				= Calcs.Names.LIAB_TURNOVER
	dataCalc['LIAB_TURN_RATE'][0]				= Calcs.Names.LIAB_TURN_RATE
	dataCalc['CHG_DEBT_REPAYMENT_REQ'][0]		= Calcs.Names.CHG_DEBT_REPAYMENT_REQ
	dataCalc['DEBTORS_PAYBACK_PERIOD'][0]		= Calcs.Names.DEBTORS_PAYBACK_PERIOD
	dataCalc['BURN_RATE'][0]					= Calcs.Names.BURN_RATE
	dataCalc['CCC'][0]							= Calcs.Names.CCC
	dataCalc['ROS'][0]							= Calcs.Names.ROS
	dataCalc['ROE'][0]							= Calcs.Names.ROE
	dataCalc['ROA'][0]							= Calcs.Names.ROA
	dataCalc['ROCE_NI'][0]						= Calcs.Names.ROCE_NI
	dataCalc['EPS_DILUTED_NI'][0]				= Calcs.Names.EPS_DILUTED_NI
	dataCalc['EPS_DILUTED_EBIT'][0]				= Calcs.Names.EPS_DILUTED_EBIT
	dataCalc['ROCE_EBIT'][0]					= Calcs.Names.ROCE_EBIT
	dataCalc['PE'][0]							= Calcs.Names.PE
	dataCalc['PE_REL_3'][0]						= Calcs.Names.PE_REL_3
	dataCalc['PE_REL_5'][0]						= Calcs.Names.PE_REL_5
	dataCalc['EARNINGS_POWER'][0]				= Calcs.Names.EARNINGS_POWER
	dataCalc['GROSS_MARGIN'][0]					= Calcs.Names.GROSS_MARGIN
	dataCalc['NOPAT_NI'][0]						= Calcs.Names.NOPAT_NI
	dataCalc['NOPAT_EBIT'][0]					= Calcs.Names.NOPAT_EBIT
	dataCalc['ROIC'][0]							= Calcs.Names.ROIC
	dataCalc['OPERATING_RATIO'][0]				= Calcs.Names.OPERATING_RATIO
	dataCalc['OP_PROFIT_MARGIN'][0]				= Calcs.Names.OP_PROFIT_MARGIN
	dataCalc['MV'][0]							= Calcs.Names.MV
	dataCalc['MV_EBIT_RATIO'][0]				= Calcs.Names.MV_EBIT_RATIO
	dataCalc['ORIG_GRAHAM'][0]					= Calcs.Names.ORIG_GRAHAM
	dataCalc['REVISED_GRAHAM'][0]				= Calcs.Names.REVISED_GRAHAM
	dataCalc['EV'][0]							= Calcs.Names.EV
	dataCalc['EV_EBIT'][0]						= Calcs.Names.EV_EBIT
	dataCalc['EV_NI'][0]						= Calcs.Names.EV_NI
	dataCalc['BV'][0]							= Calcs.Names.BV
	dataCalc['BV_PER_SHARE'][0]					= Calcs.Names.BV_PER_SHARE
	dataCalc['BV_NI'][0]						= Calcs.Names.BV_NI
	dataCalc['BV_EBIT'][0]						= Calcs.Names.BV_EBIT
	dataCalc['PRICE_SALES'][0]					= Calcs.Names.PRICE_SALES
	dataCalc['PRICE_BOOK'][0]					= Calcs.Names.PRICE_BOOK
	dataCalc['PRICE_NAV'][0]					= Calcs.Names.PRICE_NAV
	dataCalc['PRICE_FCF'][0]					= Calcs.Names.PRICE_FCF
	dataCalc['PRICE_UN_FCF'][0]					= Calcs.Names.PRICE_UN_FCF
	dataCalc['MV_OCF'][0]						= Calcs.Names.MV_OCF
	dataCalc['CASH_PRICE_RATIO'][0]				= Calcs.Names.CASH_PRICE_RATIO
	dataCalc['INTRINSIC_VALUE_NI'][0]			= Calcs.Names.INTRINSIC_VALUE_NI
	dataCalc['INTRINSIC_VALUE_EBIT'][0]			= Calcs.Names.INTRINSIC_VALUE_EBIT
	dataCalc['INTRINSIC_VALUE_FCF'][0]			= Calcs.Names.INTRINSIC_VALUE_FCF
	dataCalc['MARGIN_OF_SAFETY_NI'][0]			= Calcs.Names.MARGIN_OF_SAFETY_NI
	dataCalc['MARGIN_OF_SAFETY_EBIT'][0]		= Calcs.Names.MARGIN_OF_SAFETY_EBIT
	dataCalc['MARGIN_OF_SAFETY_FCF'][0]			= Calcs.Names.MARGIN_OF_SAFETY_FCF
	dataCalc['DUPONT_SYSTEM_1'][0]				= Calcs.Names.DUPONT_SYSTEM_1
	dataCalc['DUPONT_SYSTEM_2'][0]				= Calcs.Names.DUPONT_SYSTEM_2
	dataCalc['RETENTION_RATIO'][0]				= Calcs.Names.RETENTION_RATIO
	dataCalc['DIV_PAYOUT_RATIO'][0]				= Calcs.Names.DIV_PAYOUT_RATIO
	dataCalc['EARNINGS_YIELD'][0]				= Calcs.Names.EARNINGS_YIELD
	dataCalc['DIVS_YIELD'][0]					= Calcs.Names.DIVS_YIELD
	dataCalc['SGR'][0]							= Calcs.Names.SGR

	return dataCalc


def instantiateSectors():
	neg =  - (sys.maxsize -1)
	sectorData = {}
	sectorData['SECTOR']							= None
	sectorData['LENGTH']							= None
	sectorData['YEAR_INC'] 							= [Calcs.Names.YEAR_INC,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['YEAR_BAL']							= [Calcs.Names.YEAR_BAL,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['YEAR_CF']							= [Calcs.Names.YEAR_CF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PRICE']								= [Calcs.Names.PRICE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_NI_3YEAR']						= [Calcs.Names.AVG_NI_3YEAR,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_EBIT_3YEAR']					= [Calcs.Names.AVG_EBIT_3YEAR,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_LEV_FCF_3YEAR']					= [Calcs.Names.AVG_LEV_FCF_3YEAR,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['MARGINAL_TAX_RATE']					= [Calcs.Names.MARGINAL_TAX_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['FAIR_RETURN_RATE']					= [Calcs.Names.FAIR_RETURN_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['NO_GROWTH_PE']						= [Calcs.Names.NO_GROWTH_PE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['REQUIRED_RETURN']					= [Calcs.Names.REQUIRED_RETURN,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AAA_BOND_YIELD']					= [Calcs.Names.AAA_BOND_YIELD,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['GROWTH_MULTIPLE']					= [Calcs.Names.GROWTH_MULTIPLE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['REV_GROWTH_RATE']					= [Calcs.Names.REV_GROWTH_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EBITDA_GROWTH_RATE']				= [Calcs.Names.EBITDA_GROWTH_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EBIT_GROWTH_RATE']					= [Calcs.Names.EBIT_GROWTH_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['NI_GROWTH_RATE']					= [Calcs.Names.NI_GROWTH_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EPS_GROWTH_RATE']					= [Calcs.Names.EPS_GROWTH_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['GROWTH_RATE'] 						= [Calcs.Names.GROWTH_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_3YEARS'] 						= [Calcs.Names.AVG_3YEARS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_5YEARS'] 						= [Calcs.Names.AVG_5YEARS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['COST_OF_SALES']						= [Calcs.Names.COST_OF_SALES,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['WORKING_CAPITAL'] 					= [Calcs.Names.WORKING_CAPITAL,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CAPITAL_EMPLOYED'] 					= [Calcs.Names.CAPITAL_EMPLOYED,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['TOTAL_INVEST']						= [Calcs.Names.TOTAL_INVEST,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['TOTAL_DEBT']						= [Calcs.Names.TOTAL_DEBT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EBITDA']							= [Calcs.Names.EBITDA,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EBIAT']								= [Calcs.Names.EBIAT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EBIT']								= [Calcs.Names.EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CAPEX'] 							= [Calcs.Names.CAPEX,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['LEV_FCF']							= [Calcs.Names.LEV_FCF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['UN_LEV_FCF']						= [Calcs.Names.UN_LEV_FCF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_RECEIVABLES'] 					= [Calcs.Names.AVG_RECEIVABLES,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_PAYABLES_ACCRUALS'] 			= [Calcs.Names.AVG_PAYABLES_ACCRUALS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_WORKING_CAPITAL'] 				= [Calcs.Names.AVG_WORKING_CAPITAL,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_INVENTORY']						= [Calcs.Names.AVG_INVENTORY,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_INVEST'] 						= [Calcs.Names.AVG_INVEST,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_LT_ASSETS'] 					= [Calcs.Names.AVG_LT_ASSETS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_ASSETS'] 						= [Calcs.Names.AVG_ASSETS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_LIABILITIES']					= [Calcs.Names.AVG_LIABILITIES,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_EQUITY'] 						= [Calcs.Names.AVG_EQUITY,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['AVG_DEBT'] 							= [Calcs.Names.AVG_DEBT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CASH_RATIO']						= [Calcs.Names.CASH_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CASH_STI_RATIO']					= [Calcs.Names.CASH_STI_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CASH_SERVICE_RATIO']				= [Calcs.Names.CASH_SERVICE_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['INT_SERVICE_RATIO']					= [Calcs.Names.INT_SERVICE_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CASH_ST_DEBT_RATIO'] 				= [Calcs.Names.CASH_ST_DEBT_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ACID_TEST']							= [Calcs.Names.ACID_TEST,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['QUICK_RATIO']						= [Calcs.Names.QUICK_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['QUICK_RATIO_2']						= [Calcs.Names.QUICK_RATIO_2,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CURRENT_RATIO']						= [Calcs.Names.CURRENT_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['NWC_TO_TA']							= [Calcs.Names.NWC_TO_TA,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEBT_SERVICE_RATIO'] 				= [Calcs.Names.DEBT_SERVICE_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CHG_ST_DEBT']						= [Calcs.Names.CHG_ST_DEBT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CHG_LT_DEBT']						= [Calcs.Names.CHG_LT_DEBT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CHG_NET_DEBT']						= [Calcs.Names.CHG_NET_DEBT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['NET_DEBT'] 							= [Calcs.Names.NET_DEBT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEBT_RATIO'] 						= [Calcs.Names.DEBT_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['TOTAL_CURR_LIAB_RATIO'] 			= [Calcs.Names.TOTAL_CURR_LIAB_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['LT_DEBT_RATIO'] 					= [Calcs.Names.LT_DEBT_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEBT_EQ_RATIO'] 					= [Calcs.Names.DEBT_EQ_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEBT_TO_EBIT'] 						= [Calcs.Names.DEBT_TO_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['FIXED_CHARGE_COVERAGE'] 			= [Calcs.Names.FIXED_CHARGE_COVERAGE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEGREE_COMBINED_LEV'] 				= [Calcs.Names.DEGREE_COMBINED_LEV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEGREE_OPERATING_LEV']				= [Calcs.Names.DEGREE_OPERATING_LEV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEGREE_FINANCIAL_LEV']				= [Calcs.Names.DEGREE_FINANCIAL_LEV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DFL_RATIO'] 						= [Calcs.Names.DFL_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['FINANCIAL_LEVERAGE'] 				= [Calcs.Names.FINANCIAL_LEVERAGE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EQUITY_RATIO'] 						= [Calcs.Names.EQUITY_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EQUITY_MULTIPLIER_RATIO_1'] 		= [Calcs.Names.EQUITY_MULTIPLIER_RATIO_1,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EQUITY_MULTIPLIER_RATIO_2'] 		= [Calcs.Names.EQUITY_MULTIPLIER_RATIO_2,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['NAV'] 								= [Calcs.Names.NAV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EFFECTIVE_INT_RATE'] 				= [Calcs.Names.EFFECTIVE_INT_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEBT_COST_CAP']						= [Calcs.Names.DEBT_COST_CAP,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['WACC']								= [Calcs.Names.WACC,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['SALES_TURNOVER'] 					= [Calcs.Names.SALES_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DSO'] 								= [Calcs.Names.DSO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ASSET_TURNOVER']					= [Calcs.Names.ASSET_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ASSET_TURN_RATE']					= [Calcs.Names.ASSET_TURN_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['LT_ASSET_TURNOVER']					= [Calcs.Names.LT_ASSET_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['LT_ASSET_TURN_RATE']				= [Calcs.Names.LT_ASSET_TURN_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['INV_SALES_TURNOVER']				= [Calcs.Names.INV_SALES_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DSI']								= [Calcs.Names.DSI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['INV_COGS_TURNOVER']					= [Calcs.Names.INV_COGS_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DIO']								= [Calcs.Names.DIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['RECEIVABLES_ACCTS_TURNOVER']		= [Calcs.Names.RECEIVABLES_ACCTS_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DRO']								= [Calcs.Names.DRO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['WORKING_CAP_TURNOVER']				= [Calcs.Names.WORKING_CAP_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DWC']								= [Calcs.Names.DWC,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ROI_INVESTMENTS']					= [Calcs.Names.ROI_INVESTMENTS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CREDITORS_TURNOVER']				= [Calcs.Names.CREDITORS_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CDO']								= [Calcs.Names.CDO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PAYABLES_TURNOVER_COGS']			= [Calcs.Names.PAYABLES_TURNOVER_COGS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DPO_COGS']							= [Calcs.Names.DPO_COGS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PAYABLES_TURNOVER_COS']				= [Calcs.Names.PAYABLES_TURNOVER_COS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DPO_COS']							= [Calcs.Names.DPO_COS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['LIAB_TURNOVER']						= [Calcs.Names.LIAB_TURNOVER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['LIAB_TURN_RATE']					= [Calcs.Names.LIAB_TURN_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CHG_DEBT_REPAYMENT_REQ']			= [Calcs.Names.CHG_DEBT_REPAYMENT_REQ,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DEBTORS_PAYBACK_PERIOD']			= [Calcs.Names.DEBTORS_PAYBACK_PERIOD,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['BURN_RATE']							= [Calcs.Names.BURN_RATE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CCC']								= [Calcs.Names.CCC,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ROS']								= [Calcs.Names.ROS,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ROE']								= [Calcs.Names.ROE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ROA']								= [Calcs.Names.ROA,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ROCE_NI']							= [Calcs.Names.ROCE_NI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EPS_DILUTED_NI']					= [Calcs.Names.EPS_DILUTED_NI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EPS_DILUTED_EBIT']					= [Calcs.Names.EPS_DILUTED_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ROCE_EBIT']							= [Calcs.Names.ROCE_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PE']								= [Calcs.Names.PE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PE_REL_3']							= [Calcs.Names.PE_REL_3,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PE_REL_5']							= [Calcs.Names.PE_REL_5,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EARNINGS_POWER']					= [Calcs.Names.EARNINGS_POWER,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['GROSS_MARGIN']						= [Calcs.Names.GROSS_MARGIN,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['NOPAT_NI']							= [Calcs.Names.NOPAT_NI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['NOPAT_EBIT']						= [Calcs.Names.NOPAT_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ROIC']								= [Calcs.Names.ROIC,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['OPERATING_RATIO']					= [Calcs.Names.OPERATING_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['OP_PROFIT_MARGIN']					= [Calcs.Names.OP_PROFIT_MARGIN,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['MV']								= [Calcs.Names.MV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['MV_EBIT_RATIO']						= [Calcs.Names.MV_EBIT_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['ORIG_GRAHAM']						= [Calcs.Names.ORIG_GRAHAM,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['REVISED_GRAHAM']					= [Calcs.Names.REVISED_GRAHAM,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EV']								= [Calcs.Names.EV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EV_EBIT']							= [Calcs.Names.EV_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EV_NI']								= [Calcs.Names.EV_NI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['BV']								= [Calcs.Names.BV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['BV_PER_SHARE']						= [Calcs.Names.BV_PER_SHARE,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['BV_NI']								= [Calcs.Names.BV_NI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['BV_EBIT']							= [Calcs.Names.BV_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PRICE_SALES']						= [Calcs.Names.PRICE_SALES,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PRICE_BOOK']						= [Calcs.Names.PRICE_BOOK,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PRICE_NAV']							= [Calcs.Names.PRICE_NAV,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PRICE_FCF']							= [Calcs.Names.PRICE_FCF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['PRICE_UN_FCF']						= [Calcs.Names.PRICE_UN_FCF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['MV_OCF']							= [Calcs.Names.MV_OCF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['CASH_PRICE_RATIO']					= [Calcs.Names.CASH_PRICE_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['INTRINSIC_VALUE_NI']				= [Calcs.Names.INTRINSIC_VALUE_NI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['INTRINSIC_VALUE_EBIT']				= [Calcs.Names.INTRINSIC_VALUE_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['INTRINSIC_VALUE_FCF']				= [Calcs.Names.INTRINSIC_VALUE_FCF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['MARGIN_OF_SAFETY_NI']				= [Calcs.Names.MARGIN_OF_SAFETY_NI,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['MARGIN_OF_SAFETY_EBIT']				= [Calcs.Names.MARGIN_OF_SAFETY_EBIT,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['MARGIN_OF_SAFETY_FCF']				= [Calcs.Names.MARGIN_OF_SAFETY_FCF,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DUPONT_SYSTEM_1']					= [Calcs.Names.DUPONT_SYSTEM_1,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DUPONT_SYSTEM_2']					= [Calcs.Names.DUPONT_SYSTEM_2,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['RETENTION_RATIO']					= [Calcs.Names.RETENTION_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DIV_PAYOUT_RATIO']					= [Calcs.Names.DIV_PAYOUT_RATIO,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['EARNINGS_YIELD']					= [Calcs.Names.EARNINGS_YIELD,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['DIVS_YIELD']						= [Calcs.Names.DIVS_YIELD,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
	sectorData['SGR']								= [Calcs.Names.SGR,[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg],[neg]] 
		

	sectorData['YEAR_INC'] 							= [Calcs.Names.YEAR_INC,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['YEAR_BAL']							= [Calcs.Names.YEAR_BAL,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['YEAR_CF']							= [Calcs.Names.YEAR_CF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PRICE']								= [Calcs.Names.PRICE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_NI_3YEAR']						= [Calcs.Names.AVG_NI_3YEAR,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_EBIT_3YEAR']					= [Calcs.Names.AVG_EBIT_3YEAR,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_LEV_FCF_3YEAR']					= [Calcs.Names.AVG_LEV_FCF_3YEAR,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['MARGINAL_TAX_RATE']					= [Calcs.Names.MARGINAL_TAX_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['FAIR_RETURN_RATE']					= [Calcs.Names.FAIR_RETURN_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['NO_GROWTH_PE']						= [Calcs.Names.NO_GROWTH_PE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['REQUIRED_RETURN']					= [Calcs.Names.REQUIRED_RETURN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AAA_BOND_YIELD']					= [Calcs.Names.AAA_BOND_YIELD,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['GROWTH_MULTIPLE']					= [Calcs.Names.GROWTH_MULTIPLE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['REV_GROWTH_RATE']					= [Calcs.Names.REV_GROWTH_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EBITDA_GROWTH_RATE']				= [Calcs.Names.EBITDA_GROWTH_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EBIT_GROWTH_RATE']					= [Calcs.Names.EBIT_GROWTH_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['NI_GROWTH_RATE']					= [Calcs.Names.NI_GROWTH_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EPS_GROWTH_RATE']					= [Calcs.Names.EPS_GROWTH_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['GROWTH_RATE'] 						= [Calcs.Names.GROWTH_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_3YEARS'] 						= [Calcs.Names.AVG_3YEARS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_5YEARS'] 						= [Calcs.Names.AVG_5YEARS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['COST_OF_SALES']						= [Calcs.Names.COST_OF_SALES,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['WORKING_CAPITAL'] 					= [Calcs.Names.WORKING_CAPITAL,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CAPITAL_EMPLOYED'] 					= [Calcs.Names.CAPITAL_EMPLOYED,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['TOTAL_INVEST']						= [Calcs.Names.TOTAL_INVEST,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['TOTAL_DEBT']						= [Calcs.Names.TOTAL_DEBT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EBITDA']							= [Calcs.Names.EBITDA,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EBIAT']								= [Calcs.Names.EBIAT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EBIT']								= [Calcs.Names.EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CAPEX'] 							= [Calcs.Names.CAPEX,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['LEV_FCF']							= [Calcs.Names.LEV_FCF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['UN_LEV_FCF']						= [Calcs.Names.UN_LEV_FCF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_RECEIVABLES'] 					= [Calcs.Names.AVG_RECEIVABLES,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_PAYABLES_ACCRUALS'] 			= [Calcs.Names.AVG_PAYABLES_ACCRUALS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_WORKING_CAPITAL'] 				= [Calcs.Names.AVG_WORKING_CAPITAL,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_INVENTORY']						= [Calcs.Names.AVG_INVENTORY,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_INVEST'] 						= [Calcs.Names.AVG_INVEST,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_LT_ASSETS'] 					= [Calcs.Names.AVG_LT_ASSETS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_ASSETS'] 						= [Calcs.Names.AVG_ASSETS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_LIABILITIES']					= [Calcs.Names.AVG_LIABILITIES,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_EQUITY'] 						= [Calcs.Names.AVG_EQUITY,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['AVG_DEBT'] 							= [Calcs.Names.AVG_DEBT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CASH_RATIO']						= [Calcs.Names.CASH_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CASH_STI_RATIO']					= [Calcs.Names.CASH_STI_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CASH_SERVICE_RATIO']				= [Calcs.Names.CASH_SERVICE_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['INT_SERVICE_RATIO']					= [Calcs.Names.INT_SERVICE_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CASH_ST_DEBT_RATIO'] 				= [Calcs.Names.CASH_ST_DEBT_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ACID_TEST']							= [Calcs.Names.ACID_TEST,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['QUICK_RATIO']						= [Calcs.Names.QUICK_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['QUICK_RATIO_2']						= [Calcs.Names.QUICK_RATIO_2,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CURRENT_RATIO']						= [Calcs.Names.CURRENT_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['NWC_TO_TA']							= [Calcs.Names.NWC_TO_TA,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEBT_SERVICE_RATIO'] 				= [Calcs.Names.DEBT_SERVICE_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CHG_ST_DEBT']						= [Calcs.Names.CHG_ST_DEBT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CHG_LT_DEBT']						= [Calcs.Names.CHG_LT_DEBT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CHG_NET_DEBT']						= [Calcs.Names.CHG_NET_DEBT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['NET_DEBT'] 							= [Calcs.Names.NET_DEBT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEBT_RATIO'] 						= [Calcs.Names.DEBT_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['TOTAL_CURR_LIAB_RATIO'] 			= [Calcs.Names.TOTAL_CURR_LIAB_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['LT_DEBT_RATIO'] 					= [Calcs.Names.LT_DEBT_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEBT_EQ_RATIO'] 					= [Calcs.Names.DEBT_EQ_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEBT_TO_EBIT'] 						= [Calcs.Names.DEBT_TO_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['FIXED_CHARGE_COVERAGE'] 			= [Calcs.Names.FIXED_CHARGE_COVERAGE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEGREE_COMBINED_LEV'] 				= [Calcs.Names.DEGREE_COMBINED_LEV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEGREE_OPERATING_LEV']				= [Calcs.Names.DEGREE_OPERATING_LEV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEGREE_FINANCIAL_LEV']				= [Calcs.Names.DEGREE_FINANCIAL_LEV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DFL_RATIO'] 						= [Calcs.Names.DFL_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['FINANCIAL_LEVERAGE'] 				= [Calcs.Names.FINANCIAL_LEVERAGE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EQUITY_RATIO'] 						= [Calcs.Names.EQUITY_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EQUITY_MULTIPLIER_RATIO_1'] 		= [Calcs.Names.EQUITY_MULTIPLIER_RATIO_1,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EQUITY_MULTIPLIER_RATIO_2'] 		= [Calcs.Names.EQUITY_MULTIPLIER_RATIO_2,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['NAV'] 								= [Calcs.Names.NAV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EFFECTIVE_INT_RATE'] 				= [Calcs.Names.EFFECTIVE_INT_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEBT_COST_CAP']						= [Calcs.Names.DEBT_COST_CAP,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['WACC']								= [Calcs.Names.WACC,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['SALES_TURNOVER'] 					= [Calcs.Names.SALES_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DSO'] 								= [Calcs.Names.DSO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ASSET_TURNOVER']					= [Calcs.Names.ASSET_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ASSET_TURN_RATE']					= [Calcs.Names.ASSET_TURN_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['LT_ASSET_TURNOVER']					= [Calcs.Names.LT_ASSET_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['LT_ASSET_TURN_RATE']				= [Calcs.Names.LT_ASSET_TURN_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['INV_SALES_TURNOVER']				= [Calcs.Names.INV_SALES_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DSI']								= [Calcs.Names.DSI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['INV_COGS_TURNOVER']					= [Calcs.Names.INV_COGS_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DIO']								= [Calcs.Names.DIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['RECEIVABLES_ACCTS_TURNOVER']		= [Calcs.Names.RECEIVABLES_ACCTS_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DRO']								= [Calcs.Names.DRO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['WORKING_CAP_TURNOVER']				= [Calcs.Names.WORKING_CAP_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DWC']								= [Calcs.Names.DWC,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ROI_INVESTMENTS']					= [Calcs.Names.ROI_INVESTMENTS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CREDITORS_TURNOVER']				= [Calcs.Names.CREDITORS_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CDO']								= [Calcs.Names.CDO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PAYABLES_TURNOVER_COGS']			= [Calcs.Names.PAYABLES_TURNOVER_COGS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DPO_COGS']							= [Calcs.Names.DPO_COGS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PAYABLES_TURNOVER_COS']				= [Calcs.Names.PAYABLES_TURNOVER_COS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DPO_COS']							= [Calcs.Names.DPO_COS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['LIAB_TURNOVER']						= [Calcs.Names.LIAB_TURNOVER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['LIAB_TURN_RATE']					= [Calcs.Names.LIAB_TURN_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CHG_DEBT_REPAYMENT_REQ']			= [Calcs.Names.CHG_DEBT_REPAYMENT_REQ,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DEBTORS_PAYBACK_PERIOD']			= [Calcs.Names.DEBTORS_PAYBACK_PERIOD,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['BURN_RATE']							= [Calcs.Names.BURN_RATE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CCC']								= [Calcs.Names.CCC,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ROS']								= [Calcs.Names.ROS,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ROE']								= [Calcs.Names.ROE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ROA']								= [Calcs.Names.ROA,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ROCE_NI']							= [Calcs.Names.ROCE_NI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EPS_DILUTED_NI']					= [Calcs.Names.EPS_DILUTED_NI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EPS_DILUTED_EBIT']					= [Calcs.Names.EPS_DILUTED_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ROCE_EBIT']							= [Calcs.Names.ROCE_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PE']								= [Calcs.Names.PE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PE_REL_3']							= [Calcs.Names.PE_REL_3,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PE_REL_5']							= [Calcs.Names.PE_REL_5,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EARNINGS_POWER']					= [Calcs.Names.EARNINGS_POWER,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['GROSS_MARGIN']						= [Calcs.Names.GROSS_MARGIN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['NOPAT_NI']							= [Calcs.Names.NOPAT_NI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['NOPAT_EBIT']						= [Calcs.Names.NOPAT_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ROIC']								= [Calcs.Names.ROIC,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['OPERATING_RATIO']					= [Calcs.Names.OPERATING_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['OP_PROFIT_MARGIN']					= [Calcs.Names.OP_PROFIT_MARGIN,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['MV']								= [Calcs.Names.MV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['MV_EBIT_RATIO']						= [Calcs.Names.MV_EBIT_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['ORIG_GRAHAM']						= [Calcs.Names.ORIG_GRAHAM,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['REVISED_GRAHAM']					= [Calcs.Names.REVISED_GRAHAM,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EV']								= [Calcs.Names.EV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EV_EBIT']							= [Calcs.Names.EV_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EV_NI']								= [Calcs.Names.EV_NI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['BV']								= [Calcs.Names.BV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['BV_PER_SHARE']						= [Calcs.Names.BV_PER_SHARE,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['BV_NI']								= [Calcs.Names.BV_NI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['BV_EBIT']							= [Calcs.Names.BV_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PRICE_SALES']						= [Calcs.Names.PRICE_SALES,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PRICE_BOOK']						= [Calcs.Names.PRICE_BOOK,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PRICE_NAV']							= [Calcs.Names.PRICE_NAV,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PRICE_FCF']							= [Calcs.Names.PRICE_FCF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['PRICE_UN_FCF']						= [Calcs.Names.PRICE_UN_FCF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['MV_OCF']							= [Calcs.Names.MV_OCF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['CASH_PRICE_RATIO']					= [Calcs.Names.CASH_PRICE_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['INTRINSIC_VALUE_NI']				= [Calcs.Names.INTRINSIC_VALUE_NI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['INTRINSIC_VALUE_EBIT']				= [Calcs.Names.INTRINSIC_VALUE_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['INTRINSIC_VALUE_FCF']				= [Calcs.Names.INTRINSIC_VALUE_FCF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['MARGIN_OF_SAFETY_NI']				= [Calcs.Names.MARGIN_OF_SAFETY_NI,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['MARGIN_OF_SAFETY_EBIT']				= [Calcs.Names.MARGIN_OF_SAFETY_EBIT,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['MARGIN_OF_SAFETY_FCF']				= [Calcs.Names.MARGIN_OF_SAFETY_FCF,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DUPONT_SYSTEM_1']					= [Calcs.Names.DUPONT_SYSTEM_1,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DUPONT_SYSTEM_2']					= [Calcs.Names.DUPONT_SYSTEM_2,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['RETENTION_RATIO']					= [Calcs.Names.RETENTION_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DIV_PAYOUT_RATIO']					= [Calcs.Names.DIV_PAYOUT_RATIO,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['EARNINGS_YIELD']					= [Calcs.Names.EARNINGS_YIELD,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['DIVS_YIELD']						= [Calcs.Names.DIVS_YIELD,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	sectorData['SGR']								= [Calcs.Names.SGR,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]] 
	return sectorData