import inspect

#TODO: Naming Convention Updates:
#TOTAL_INT_ASSETS is now TOTAL_INTANG_ASSETS
#OTH_INT_ASSETS is now OTH_INTANG_ASSETS
#DISP_INTAG_ASSETS is now DISP_INTANG_ASSETS
#ACQ_INTAG_ASSETS is now ACQ_INTANG_ASSETS
#ACQ_FIXED_INTAG is now ACQ_FIXED_INTANG
#STI is now ST_INVEST
#CHG_ACCTS_REC is now CREDIT_SALES
#INC_TAX_BENEFIT is now INC_TAX_EXPENSE
#CASH_INVEST_ACT2 is now TOTAL_INVEST
#TOTAL_INVEST is now CASH_INVEST (in cashflow)

#TODO: Compare all duplicates: Put in PythonApplication1. If Unused, delete them all.
#i=0
#while(i < 35):
#	if(data['NET_EXTRA1'][i] != data['NET_EXTRA2'][i]):
#		print('NET_EXTRA1 != NET_EXTRA2')
#	if(data['TOTAL_ASSETS1'][i] != data['TOTAL_ASSETS2'][i]):
#		print('TOTAL_ASSETS1 != TOTAL_ASSETS2')
#	if(data['DERIV_HEDGE_ASSETS1'][i] != data['DERIV_HEDGE_ASSETS2'][i]):
#		print('DERIV_HEDGE_ASSETS1 != DERIV_HEDGE_ASSETS2')
#	if(data['NET_CASH_DISC_OPS1'][i] != data['NET_CASH_DISC_OPS2'][i] != data['NET_CASH_DISC_OPS3'][i]):
#		print('NET_CASH_DISC_OPS1 != NET_CASH_DISC_OPS1 != NET_CASH_DISC_OPS3')
#	if(data['DEFF_REV_1'][i] != data['DEFF_REV_2'][i]):
#		print('DEFF_REV_1 != DEFF_REV_2')
#	if(data['DERIV_HEDGE_1'][i] != data['DERIV_HEDGE_2'][i]):
#		print('DERIV_HEDGE_1 != DERIV_HEDGE_2')
#	if(data['NET_CASH_DISC_OPS1'][i] != data['NET_CASH_DISC_OPS2'][i]):
#		print('NET_CASH_DISC_OPS1 != NET_CASH_DISC_OPS2')
#	if(data['CASH_INVEST_ACT1'][i] != data['CASH_INVEST_ACT2'][i]):
#		print('CASH_INVEST_ACT1 != CASH_INVEST_ACT2')
#	if(data['CASH_FIN_ACT1'][i] != data['CASH_FIN_ACT2'][i]):
#		print('CASH_FIN_ACT1 != CASH_FIN_ACT2')
#	i += 1

class fin(str):
	# data Values
	REV = "Net Revenue after Provisions"
	COST_OF_REV = "Total Non-Interest Expense"
	OP_INC_LOSS = "Operating Income (Loss)"
	PRETAX_INCOME = "Pretax Income (Loss), GAAP"

	# dataCalc values
	TOTAL_INVEST = "ST And LT Investments"


class inc(str):
	YEAR_INC					= "In Millions of USD except Per Share"
	REV							= "Revenue"
	SALES_SERV_REV				= "Sales & Services Revenue"
	OTHER_REV					= "Other Revenue"
	COST_OF_REV					= "Cost of Revenue"
	COGS						= "Cost of Goods & Services"
	PROFIT						= "Gross Profit"
	OTH_PROFIT					= "Other Operating Income"			
	OP_EXP						= "Operating Expenses"		
	SG_AND_ADMIN				= "Selling, General & Admin"
	SELL_AND_MARK				= "Selling & Marketing"	
	GEN_AND_ADMIN				= "General & Administrative"
	R_AND_D 					= "Research & Development"
	DEP_AMORT					= "Depreciation & Amortization"
	OTH_OP_EXP					= "Other Operating Expense"
	OP_INC_LOSS					= "Operating Income (Loss)"
	NON_OP_INC_LOSS				= "Non-Operating (Income) Loss"
	NET_INT_EXP					= "Interest Expense, Net"
	INT_EXP						= "Interest Expense"
	INT_INC						= "Interest Income"
	FOREX						= "Foreign Exch (Gain) Loss"
	AFFILIATES					= "(Income) Loss from Affiliates"
	NON_OP_INC					= "Other Non-Op (Income) Loss"
	PRETAX_INCOME				= "Pretax Income"
	INC_TAX_EXPENSE				= "Income Tax Expense (Benefit)"
	CURR_INC_TAX				= "Current Income Tax"
	DEFF_INC_TAX				= "Deferred Income Tax"
	CONT_OPS					= "Income (Loss) from Cont Ops"
	NET_EXTRA1					= "Net Extraordinary Losses (Gains)"
	DISC_OPS					= "Discontinued Operations"
	ACCT_CHNG					= "XO & Accounting Changes"
	INCOME_MI					= "Income (Loss) Incl. MI"
	MIN_INTEREST				= "Minority Interest"
	NI_INC  					= "Net Income, GAAP"
	PREF_DIVS					= "Preferred Dividends"
	OTH_ADJ						= "Other Adjustments"
	NI_AVAIL_COMMON_GAAP		= "Net Income Avail to Common, GAAP"
	NI_AVAIL_COMMON_ADJ			= "Net Income Avail to Common, Adj"
	NET_ABNORMAL				= "Net Abnormal Losses (Gains)"
	NET_EXTRA2					= "Net Extraordinary Losses (Gains)"
	BASIC_WEIGHT_AVG_SHARES		= "Basic Weighted Avg Shares"
	DIL_WEIGHT_AVG_SHARES		= "Diluted Weighted Avg Shares"

class bal(str):
	YEAR_BAL					= "In Millions of USD except Per Share"
	TOTAL_ASSETS1				= "Total Assets"						 
	CASH_EQ_STI					= "Cash, Cash Equivalents & STI"		 
	CASH_EQ						= "Cash & Cash Equivalents"				 
	ST_INVEST					= "ST Investments"						 
	ACCTS_REC					= "Accounts & Notes Receiv"				 
	ACCTS_REC_NET				= "Accounts Receivable, Net"			 
	NOTES_REC_NET				= "Notes Receivable, Net"				 
	INV							= "Inventories"							 
	RAW_MAT						= "Raw Materials"						 
	WIP							= "Work In Process"						 
	FIN_GOODS 					= "Finished Goods"						 
	OTH_INV						= "Other Inventory"						 
	OTH_ST_ASSETS				= "Other ST Assets"						 
	DERIV_HEDGE_ASSETS1			= "Derivative & Hedging Assets"		
	TAXES_RECIEV				= "Taxes Receivable"
	MISC_ST_ASSETS				= "Misc ST Assets"						 
	TOTAL_CURR_ASSETS			= "Total Current Assets"				 
	PPE_NET						= "Property, Plant & Equip, Net"		 
	PPE							= "Property, Plant & Equip"				 
	ACC_DEPREC					= "Accumulated Depreciation"			 
	LTI_RECEIVABLES				= "LT Investments & Receivables"
	LT_INVEST					= "LT Investments"
	OTH_LT_ASSETS				= "Other LT Assets"						 
	TOTAL_INTANG_ASSETS			= "Total Intangible Assets"				 
	GOODWILL					= "Goodwill"							 
	OTH_INTANG_ASSETS			= "Other Intangible Assets"	
	PREPAID_EXP					= "Prepaid Expense"
	DEFF_TAX_ASSETS				= "Deferred Tax Assets"					 
	DERIV_HEDGE_ASSETS2			= "Derivative & Hedging Assets"			 
	MISC_ASSETS					= "Misc LT Assets"						 
	TOTAL_NON_CURR_ASSETS		= "Total Noncurrent Assets"				 
	TOTAL_ASSETS2				= "Total Assets"						 
	PAYABLES_ACCRUALS			= "Payables & Accruals"					 
	PAYABLES					= "Accounts Payable"					 
	ACCRUED_TAXES				= "Accrued Taxes"						 
	INT_DIVS_PAYABLES			= "Interest & Dividends Payable"		 
	OTH_PAYABLES_ACCURALS		= "Other Payables & Accruals"			 
	ST_DEBT						= "ST Debt"								 
	ST_BORROWINGS				= "ST Borrowings"						 
	ST_FIN_LEASES				= "ST Finance Leases"					 
	ST_OP_LEASES				= "ST Operating Leases"					 
	CURR_LT_DEBT				= "Current Portion of LT Debt"			 
	OTH_ST_LIAB					= "Other ST Liabilities"				 
	DEFF_REV_1					= "Deferred Revenue"					 
	DERIV_HEDGE_1				= "Derivatives & Hedging"				 
	MISC_ST_LIAB				= "Misc ST Liabilities"					 
	TOTAL_CURR_LIAB				= "Total Current Liabilities"			 
	LT_DEBT						= "LT Debt"								 
	LT_BORROW					= "LT Borrowings"						 
	LT_FIN_LEASES				= "LT Finance Leases"					 
	LT_OP_LEASES				= "LT Operating Leases"					 
	OTH_LT_LIAB					= "Other LT Liabilities"				 
	ACCURED_LIAB				= "Accrued Liabilities"					 
	PENSION_LIAB				= "Pension Liabilities"		
	PENSIONS					= "Pensions"
	OTH_POST_RET_BEN			= "Other Post-Ret Benefits"
	DEFF_REV_2					= "Deferred Revenue"
	DEF_TAX_LIAB				= "Deferred Tax Liabilities"
	DERIV_HEDGE_2				= "Derivatives & Hedging"				 
	MISC_LT_LIAB				= "Misc LT Liabilities"					 
	TOTAL_NON_CURR_LIAB			= "Total Noncurrent Liabilities"		 
	TOTAL_LIAB					= "Total Liabilities"					 
	PREF_EQUITY_HYBRID_CAP		= "Preferred Equity and Hybrid Capital"	 
	SHARE_CAP_APIC				= "Share Capital & APIC"				 
	COMMON_STOCK				= "Common Stock"						 
	ADD_PAID_CAP				= "Additional Paid in Capital"			 
	TREASURY_STOCK				= "Treasury Stock"						 
	RE							= "Retained Earnings"					 
	OTH_EQUITY					= "Other Equity"						 
	EQUITY_BEFORE_MIN_INT		= "Equity Before Minority Interest"		 
	MIN_NON_CONTROL_INT			= "Minority/Non Controlling Interest"	 
	TOTAL_EQUITY				= "Total Equity"						 
	LIAB_AND_EQUITY				= "Total Liabilities & Equity"			 
	
class cf(str):
	YEAR_CF						 = "In Millions of USD except Per Share"
	NI_CF  						 = "Net Income"							  
	DEPRE_AMORT					 = "Depreciation & Amortization"			
	NON_CASH_ITEMS				 = "Non-Cash Items"						  
	STOCK_COMP					 = "Stock-Based Compensation"			  
	DEF_INT_COMP				 = "Deferred Income Taxes"				  
	OTH_NON_CASH_ADJ			 = "Other Non-Cash Adj"					  
	CHG_NON_CASH_OP				 = "Chg in Non-Cash Work Cap"			  
	CREDIT_SALES				 = "(Inc) Dec in Accts Receiv"			  
	CHG_INVENTORIES				 = "(Inc) Dec in Inventories"			  
	CHG_ACCTS_PAYABLE			 = "Inc (Dec) in Accts Payable"			  
	CHG_OTHER					 = "Inc (Dec) in Other"					  
	NET_CASH_DISC_OPS1			 = "Net Cash From Disc Ops"				  
	CASH_OP_ACT					 = "Cash from Operating Activities"		  
	CASH_INVEST_ACT1			 = "Cash from Investing Activities"		  
	CHG_FIXED_INTANG			 = "Change in Fixed & Intang"			  
	DISP_FIXED_INTANG			 = "Disp in Fixed & Intang"				  
	DISP_FIXED_PROD_ASSETS		 = "Disp of Fixed Prod Assets"			  
	DISP_INTANG_ASSETS			 = "Disp of Intangible Assets"			  
	ACQ_FIXED_INTANG			 = "Acq of Fixed & Intang"				  
	ACQ_FIXED_PROD_ASSETS		 = "Acq of Fixed Prod Assets"			  
	ACQ_INTANG_ASSETS			 = "Acq of Intangible Assets"			  
	NET_CHG_LT_INVEST			 = "Net Change in LT Investment"			
	DEC_LT_INVEST				 = "Dec in LT Investment"				  
	INC_LT_INVEST				 = "Inc in LT Investment"				  
	NET_CASH_ACQ_DIV			 = "Net Cash From Acq & Div"				
	CASH_DIVEST					 = "Cash from Divestitures"				  
	CASH_ACQ_SUBS				 = "Cash for Acq of Subs"				  
	CASH_JVS					 = "Cash for JVs"						  
	OTH_INVEST_ACT				 = "Other Investing Activities"			  
	NET_CASH_DISC_OPS2			 = "Net Cash From Disc Ops"				  
	CASH_INVEST					 = "Cash from Investing Activities"		  
	CASH_FIN_ACT1				 = "Cash from Financing Activities"		  
	DIVS_PAID					 = "Dividends Paid"						  
	CASH_REPAY_DEBT				 = "Cash From (Repayment) Debt"			  
	CASH_ST_DEBT				 = "Cash From (Repay) ST Debt"			  
	CASH_LT_DEBT				 = "Cash From LT Debt"					  
	REPAY_LT_DEBT				 = "Repayments of LT Debt"				  
	CASH_REPURCH_EQUITY			 = "Cash (Repurchase) of Equity"			
	INC_CAPITAL_STOCK			 = "Increase in Capital Stock"			  
	DEC_CAPITAL_STOCK			 = "Decrease in Capital Stock"			  
	OTH_FIN_ACT					 = "Other Financing Activities"			  
	NET_CASH_DISC_OPS3			 = "Net Cash From Disc Ops"				  
	CASH_FIN_ACT2				 = "Cash from Financing Activities"		  
	EFFECT_FOREX_RATES			 = "Effect of Foreign Exchange Rates"	  
	NET_CHG_CASH				 = "Net Changes in Cash"					
	CASH_PAID_TAXES				 = "Cash Paid for Taxes"					
	CASH_PAID_INT				 = "Cash Paid for Interest"

class ticker(float):
	#inc
	YEAR_INC					= [None] * 35
	REV						    = [None] * 35
	SALES_SERV_REV				= [None] * 35
	OTHER_REV				    = [None] * 35
	COST_OF_REV					= [None] * 35
	COGS						= [None] * 35
	PROFIT					    = [None] * 35
	OTH_PROFIT				    = [None] * 35
	OP_EXP					    = [None] * 35
	SG_AND_ADMIN				= [None] * 35
	SELL_AND_MARK				= [None] * 35
	GEN_AND_ADMIN				= [None] * 35
	R_AND_D					    = [None] * 35
	DEP_AMORT				    = [None] * 35
	OTH_OP_EXP				    = [None] * 35
	OP_INC_LOSS				    = [None] * 35
	NON_OP_INC_LOSS			    = [None] * 35
	NET_INT_EXP				    = [None] * 35
	INT_EXP					    = [None] * 35
	INT_INC					    = [None] * 35
	FOREX					    = [None] * 35
	AFFILIATES				    = [None] * 35
	NON_OP_INC				    = [None] * 35
	PRETAX_INCOME			    = [None] * 35
	INC_TAX_EXPENSE			    = [None] * 35
	CURR_INC_TAX			    = [None] * 35
	DEFF_INC_TAX			    = [None] * 35
	CONT_OPS				    = [None] * 35
	NET_EXTRA1				    = [None] * 35
	DISC_OPS				    = [None] * 35
	ACCT_CHNG				    = [None] * 35
	INCOME_MI				    = [None] * 35
	MIN_INTEREST			    = [None] * 35
	NI_INC  					= [None] * 35
	PREF_DIVS				    = [None] * 35
	OTH_ADJ					    = [None] * 35
	NI_AVAIL_COMMON_GAAP	    = [None] * 35
	NI_AVAIL_COMMON_ADJ		    = [None] * 35
	NET_ABNORMAL			    = [None] * 35
	NET_EXTRA2				    = [None] * 35
	BASIC_WEIGHT_AVG_SHARES     = [None] * 35
	DIL_WEIGHT_AVG_SHARES	    = [None] * 35
	#bal
	YEAR_BAL					= [None] * 35
	TOTAL_ASSETS1				= [None] * 35
	CASH_EQ_STI					= [None] * 35
	CASH_EQ						= [None] * 35
	ST_INVEST					= [None] * 35
	TOTAL_INVEST				= [None] * 35
	ACCTS_REC					= [None] * 35
	ACCTS_REC_NET				= [None] * 35
	NOTES_REC_NET				= [None] * 35
	INV							= [None] * 35
	RAW_MAT						= [None] * 35
	WIP							= [None] * 35
	FIN_GOODS 					= [None] * 35
	OTH_INV						= [None] * 35
	OTH_ST_ASSETS				= [None] * 35
	DERIV_HEDGE_ASSETS1			= [None] * 35
	TAXES_RECIEV				= [None] * 35
	MISC_ST_ASSETS				= [None] * 35
	TOTAL_CURR_ASSETS			= [None] * 35
	PPE_NET						= [None] * 35
	PPE							= [None] * 35
	ACC_DEPREC					= [None] * 35
	LTI_RECEIVABLES				= [None] * 35
	LT_INVEST					= [None] * 35
	OTH_LT_ASSETS				= [None] * 35
	TOTAL_INTANG_ASSETS			= [None] * 35
	GOODWILL					= [None] * 35
	OTH_INTANG_ASSETS			= [None] * 35
	PREPAID_EXP					= [None] * 35
	DEFF_TAX_ASSETS				= [None] * 35
	DERIV_HEDGE_ASSETS2			= [None] * 35
	MISC_ASSETS					= [None] * 35
	TOTAL_NON_CURR_ASSETS		= [None] * 35
	TOTAL_ASSETS2				= [None] * 35
	LIAB_AND_EQUITY1			= [None] * 35
	PAYABLES_ACCRUALS			= [None] * 35
	PAYABLES					= [None] * 35
	ACCRUED_TAXES				= [None] * 35
	INT_DIVS_PAYABLES			= [None] * 35
	OTH_PAYABLES_ACCURALS		= [None] * 35
	ST_DEBT						= [None] * 35
	ST_BORROWINGS				= [None] * 35
	ST_FIN_LEASES				= [None] * 35
	ST_OP_LEASES				= [None] * 35
	CURR_LT_DEBT				= [None] * 35
	OTH_ST_LIAB					= [None] * 35
	DEFF_REV_1					= [None] * 35
	DERIV_HEDGE_1				= [None] * 35
	MISC_ST_LIAB				= [None] * 35
	TOTAL_CURR_LIAB				= [None] * 35
	LT_DEBT						= [None] * 35
	LT_BORROW					= [None] * 35
	LT_FIN_LEASES				= [None] * 35
	LT_OP_LEASES				= [None] * 35
	OTH_LT_LIAB					= [None] * 35
	ACCURED_LIAB				= [None] * 35
	PENSION_LIAB				= [None] * 35
	PENSIONS					= [None] * 35
	OTH_POST_RET_BEN			= [None] * 35
	DEFF_REV_2					= [None] * 35
	DEF_TAX_LIAB				= [None] * 35
	DERIV_HEDGE_2				= [None] * 35
	MISC_LT_LIAB				= [None] * 35
	TOTAL_NON_CURR_LIAB			= [None] * 35
	TOTAL_LIAB					= [None] * 35
	PREF_EQUITY_HYBRID_CAP		= [None] * 35
	SHARE_CAP_APIC				= [None] * 35
	COMMON_STOCK				= [None] * 35
	ADD_PAID_CAP				= [None] * 35
	TREASURY_STOCK				= [None] * 35
	RE							= [None] * 35
	OTH_EQUITY					= [None] * 35
	EQUITY_BEFORE_MIN_INT		= [None] * 35
	MIN_NON_CONTROL_INT			= [None] * 35
	TOTAL_EQUITY				= [None] * 35
	LIAB_AND_EQUITY				= [None] * 35
	#cf
	YEAR_CF						= [None] * 35
	NI_CF  						= [None] * 35
	DEPRE_AMORT					= [None] * 35
	NON_CASH_ITEMS				= [None] * 35
	STOCK_COMP					= [None] * 35
	DEF_INT_COMP				= [None] * 35
	OTH_NON_CASH_ADJ			= [None] * 35
	CHG_NON_CASH_OP				= [None] * 35
	CREDIT_SALES				= [None] * 35
	CHG_INVENTORIES				= [None] * 35
	CHG_ACCTS_PAYABLE			= [None] * 35
	CHG_OTHER					= [None] * 35
	NET_CASH_DISC_OPS1			= [None] * 35
	CASH_OP_ACT					= [None] * 35
	CASH_INVEST_ACT1			= [None] * 35
	CHG_FIXED_INTANG			= [None] * 35
	DISP_FIXED_INTANG			= [None] * 35
	DISP_FIXED_PROD_ASSETS		= [None] * 35
	DISP_INTANG_ASSETS			= [None] * 35
	ACQ_FIXED_INTANG			= [None] * 35
	ACQ_FIXED_PROD_ASSETS		= [None] * 35
	ACQ_INTANG_ASSETS			= [None] * 35
	NET_CHG_LT_INVEST			= [None] * 35
	DEC_LT_INVEST				= [None] * 35
	INC_LT_INVEST				= [None] * 35
	NET_CASH_ACQ_DIV			= [None] * 35
	CASH_DIVEST					= [None] * 35
	CASH_ACQ_SUBS				= [None] * 35
	CASH_JVS					= [None] * 35
	OTH_INVEST_ACT				= [None] * 35
	NET_CASH_DISC_OPS2			= [None] * 35
	CASH_FIN_ACT1				= [None] * 35
	DIVS_PAID					= [None] * 35
	CASH_REPAY_DEBT				= [None] * 35
	CASH_ST_DEBT				= [None] * 35
	CASH_LT_DEBT				= [None] * 35
	REPAY_LT_DEBT				= [None] * 35
	CASH_REPURCH_EQUITY			= [None] * 35
	INC_CAPITAL_STOCK			= [None] * 35
	DEC_CAPITAL_STOCK			= [None] * 35
	OTH_FIN_ACT					= [None] * 35
	NET_CASH_DISC_OPS3			= [None] * 35
	CASH_FIN_ACT2				= [None] * 35
	EFFECT_FOREX_RATES			= [None] * 35
	NET_CHG_CASH				= [None] * 35
	CASH_PAID_TAXES				= [None] * 35
	CASH_PAID_INT				= [None] * 35
	